<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

const LOCATION_TYPE = 'Location Type';
$viewModel = $block->getData('view_model');
?>
<div class="page_title">
    <h1><?= $block->escapeHtml(__('My Orders')) ?></h1>
</div>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <th scope="col" class="col location"><?= $block->escapeHtml(__(LOCATION_TYPE)) ?></th>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>"
                    class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>"
                     class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php if (!$_order->getIsVirtual()): ?>
                        <?php $_shippingAddress = $_order->getShippingAddress(); ?>
                        <td data-th="<?= $block->escapeHtml(__(LOCATION_TYPE)) ?>"
                         class="col location">
                         <?= $block->escapeHtml($viewModel->getLocationType(
                            $_shippingAddress->getData()['customer_address_id'] ?? null)); ?>
                            </td>
                    <?php else: ?>
                        <td data-th="<?= $block->escapeHtml(__(LOCATION_TYPE)) ?>"
                         class="col location"></td>
                    <?php endif; ?>

                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>"
                     class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                     class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <div class="action_primary">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if
                            ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId()))
                             : ?>
                            <a href="#" data-post='<?= /* @noEscape */
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= $block->escapeHtml(__('Reorder (All Items)')) ?></span>
                            </a>
                        </div>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <!-- change message 08/03/2022[BS] -->
    <div class="message info empty"><span><?= $block->escapeHtml('You have placed no orders.') ?></span></div>
<?php endif ?>
