<?php
/** @var Magento\CustomerCustomAttributes\Block\Form $block */
// phpcs:disable Magento2.Templates.ThisInTemplate
use Magento\Customer\Block\Widget\Dob;
use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name;
use Magento\Customer\Block\Widget\Taxvat;

?>
<?php
$block= $block->getLayout()->createBlock(Magento\Customer\Block\Form\Edit::class);

$helper = $this->helper(HookahShisha\ChangePassword\Helper\Data::class);
?>
<?php if ($helper->customerLoggedIn()): ?>
    <?php $firstname = $helper->customerFirstName(); ?>
    <?php $lastname = $helper->customerLastName(); ?>
<div class="page_title">
    <h1><?= $block->escapeHtml(__('Change Password')) ?></h1>
</div>
<form class="form registerform" action="<?= /* @noEscape */ $block->getUrl('changepassword/account/changepwd') ?>"
      method="post" id="form-validate" enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>" autocomplete="off"
>
    <?= $block->getBlockHtml('formkey') ?>

    <div class="fieldset field_flex password" data-container="change-email-password">
      
        <div class="field field_block password current required">
            <label class="label" for="current-password">
                <span><?= $block->escapeHtml(__('Current Password')) ?></span>
            </label>
            <div class="control">
                <input type="password" class="input-text"
                 placeholder="<?= $block->escapeHtml(__('Current Password')) ?>"
                 name="current_password" id="current-password"
                       data-input="current-password"  
                       data-validate="{required:true, 'validate-password':true}" autocomplete="off"
                />
                <a class="fa fa-eye-slash" id="showlgpass" data-vis="0" title=""></a>
            </div>
        </div>
    
     <input type="hidden" name="change_password" id="change-password" data-role="change-password" value="1">
     <input type="hidden" name="firstname" id="firstname" value="<?= /* @noEscape */ $firstname;?>">
     <input type="hidden" name="lastname" id="lastname" value="<?= /* @noEscape */ $lastname;?>">
     <input type="hidden" name="custom_change_password" id="custom_change_password" value="1">

        <div class="field new password required" data-container="new-password">
            <label class="label" for="password">
                <span><?= $block->escapeHtml(__('New Password')) ?></span>
            </label>
            <div class="control">
                <?php $minCharacterSets = $block->getRequiredCharacterClassesNumber() ?>
                <input type="password" class="input-text" 
                placeholder="<?= $block->escapeHtml(__('New Password')) ?>" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtml($minCharacterSets) ?>"
                       data-input="new-password"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off" />
                <a class="fa fa-eye-slash" id="showlgpass" data-vis="0" title=""></a>
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation">
                <span><?= $block->escapeHtml(__('Confirm New Password')) ?></span>
            </label>
            <div class="control">
                <input type="password" class="input-text" 
                placeholder="<?= $block->escapeHtml(__('Confirm Password')) ?>"
                 name="password_confirmation" id="password-confirmation"
                       data-input="confirm-password" 
                       data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                />
                <a class="fa fa-eye-slash" id="showlgpass" data-vis="0" title=""></a>
            </div>
        </div>

    </div>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save Details')) ?></span>
            </button>
        </div>
    </div>
</form>
<?php endif; ?>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        dataForm.mage('validation', {});
       
    });
</script>
<script type="text/x-magento-init">
    {    
           
        "*": {
             "Magento_CustomerCustomAttributes/validation": {
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            },

            "Magento_Ui/js/core/app": {
                "components": {
                    "showPassword": {
                        "component": "Magento_Customer/js/show-password",
                        "passwordSelector": "#current-password,#password,#password-confirmation"
                    }
                }
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.registerform"
            }
        }
    }
</script>
