<?php
/**
 * Blog sidebar archive template
 *
 */
/** @var \Magefan\Blog\Block\Sidebar\Archive $block */
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<?php
    $_years = $block->getMonths();
?>
<?php if (count($_years)) { ?>
<div class="widget block block-archive" data-bind="scope: 'blog-archive'">
    <div class="block-title">
        <?= $block->escapeHtml(__('Month List')) ?>
    </div>
    <div id="month_list_collapse" class="block-content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "multipleCollapsible": false}}'>
        <?php foreach ($_years as $_year => $_months): ?>
            <?php if (count($_months)): ?>
                <div data-role="collapsible">
                    <div data-role="trigger">
                        <span><?= $block->escapeHtml($_year); ?></span>
                    </div>
                    <div class="collapse-content" data-role="content">
                        <?php foreach ($_months as $time): ?>
                            <?php
                                $title = $block->getTranslatedDate($time);
                            ?>
                            <div class="item">
                                <a title="<?= $block->escapeHtml(__('Archive %1', $title)) ?>"
                                   class="archive-item-link"
                                   href="<?= $block->escapeUrl($block->getTimeUrl($time)) ?>">
                                    <?= $block->escapeHtml($title); ?>
                                </a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<?php } ?>
<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#month_list_collapse").accordion();
    });
</script>
