<?php

/** @var \Avalara\Excise\Block\Adminhtml\Log\Summary $block */
$summaryData = $block->getSummaryData();
?>
<div class="admin__avatax-log-summary">
    <span class="avatax-log-summary-title"><?= /* @noEscape */  __('Summary'); ?></span>
    <div class="avatax-summary-list">
    <?php foreach ($summaryData as $level): ?>
        <div class="avatax-log-summary-level">
            <span class="avatax-log-summary-level-label"><?= /* @noEscape */ $level['level']; ?></span>
            <span class="avatax-log-summary-count"><?= /* @noEscape */ $level['count']; ?></span>
        </div>
    <?php endforeach; ?>
    </div>
</div>
