<?php
/** @var \HookahShisha\Customerb2b\Block\Myaccount\Basicdetail $block */
/** @var \Magento\Customer\ViewModel\Address $viewModel */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
// phpcs:disable Magento2.Templates.ThisInTemplate
$viewModel = $block->getViewModel();
$actionURL = "#";
$formDisable = 1;
?>
<?php $hub_mobile_number = $block->getCustomer()->getCustomAttribute('hub_mobile_number');?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php $_country_id = $block->getAttributeData()->getFrontendLabel('country_id'); ?>
<?php $_street = $block->getAttributeData()->getFrontendLabel('street'); ?>
<?php $_city = $block->getAttributeData()->getFrontendLabel('city'); ?>
<?php $_selectRegion = 'Please select a region, state or province.'; ?>
<?php $_displayAll = $block->getConfig('general/region/display_all'); ?>
<?php $_county = $block->getAttributeData()->getFrontendLabel('county'); ?>


<?php $_vatidValidationClass = $viewModel->addressGetAttributeValidationClass('vat_id'); ?>
<?php $_cityValidationClass = $viewModel->addressGetAttributeValidationClass('city'); ?>
<?php $_postcodeValidationClass_value = $viewModel->addressGetAttributeValidationClass('postcode'); ?>
<?php $_postcodeValidationClass = $_postcodeValidationClass_value; ?>
<?php $_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street'); ?>
<?php $_streetValidationClassNotRequired = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
<?php $_regionValidationClass = $viewModel->addressGetAttributeValidationClass('region'); ?>
<?php
/* Start Change the region_id Label if the Country is US for State and Other for the State */
$regionStateLabel = $block->escapeHtml(__('State'));
$regionProvinceLabel = $block->escapeHtml(__('Province'));
$_region = ($block->getCountryId() == 'US')?$regionStateLabel:$regionProvinceLabel;
/* End Change the region_id Label if the Country is US for State and Other for the State */
?>
<?php $messageData = $block->getMessagedata(); ?>
<?php if ($messageData['cstAccountVerified'] == 0 && $messageData['cstDetailsChanged'] == 0): ?>
    <?php $actionURL = $this->getUrl('customerb2b/account/basicPost'); ?>
    <?php $formDisable = 0; ?>
<?php endif; ?>

<form class="form-address-edit"
      action="<?= $block->escapeUrl($this->getUrl('customerb2b/account/basicPost')) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend></legend>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
        <input type="hidden" name="id" value="<?= /* @noEscape */ $block->getCustomer()->getDefaultBilling(); ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>
        <div class="field">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" 
                        name="email" 
                        id="email_address" 
                        placeholder="<?php /* @noEscape */ __('Email') ?>"
                        autocomplete="off" 
                        value="<?= /* @noEscape */ $block->escapeHtml($block->getCustomer()->getEmail()) ?>" 
                        title="<?php /* @noEscape */ __('Email') ?>" 
                        class="input-text"
                        disabled="disabled"
                        readonly="readonly"/>
            </div>
        </div>
        <?php if ($_telephone->isEnabled()): ?>
            <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>

        <?php if ($_fax->isEnabled()): ?>
            <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>
        <div class="field country required">
            <label class="label" for="country">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
            </label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>  
        <div class="field mobile">
            <label for="hub_mobile_number" class="label">
                <span><?= $block->escapeHtml(__('Mobile Number')) ?>                    
                </span>
            </label>
            <?php $hub_mobile_number = $hub_mobile_number ? $hub_mobile_number->getValue() : "" ?> 
            <div class="control">
                <input type="text" 
                        name="hub_mobile_number" 
                        id="hub_mobile_number" 
                        placeholder="<?= $block->escapeHtml(__('Mobile Number')) ?>"
                        value="<?= /* @noEscape */ $hub_mobile_number ?>" 
                        title="<?php /* @noEscape */ __('Mobile Number') ?>" 
                        class="input-text" />
            </div>
        </div> 
    </fieldset>
    <fieldset class="fieldset">
        <legend></legend>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= $block->escapeHtml(__($_street . ' 1')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= $block->escapeHtml(__($_street . ' 1')) ?>"
                       placeholder="<?= $block->escapeHtml(__($_street . ' 1')) ?>"
                       id="street_1"
                       class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>"/>
                <div class="nested">
                    <?php for ($_i = 1, $_n = $viewModel->addressGetStreetLines(); $_i < $_n; $_i++): ?>
                                <?php $lineI=$_i+1 ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__($_street." ".$lineI)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $escaper->escapeHtmlAttr(__($_street." ".$lineI)) ?>"
                                       placeholder="<?= $escaper->escapeHtmlAttr(__($_street." ".$lineI)) ?>"
                                       id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                       class="input-text
                                        <?= $escaper->escapeHtmlAttr($_streetValidationClassNotRequired) ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <div class="field city required">
            <label class="label" for="city">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       class="input-text wholesalers-validate-text
                        <?= $escaper->escapeHtmlAttr($_cityValidationClass) ?>"
                       id="city">
            </div>
        </div>

        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       id="zip"
                       class="input-text validate-zip-international wholesalers-validate-text
                        <?= $escaper->escapeHtmlAttr($_postcodeValidationClass) ?>">
                <div role="alert" class="message warning">
                    <span></span>
                </div>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div.message.warning') ?>
            </div>
        </div>

        <div class="field region required">
            <label class="label" for="region_id" id="region_id_label">
                <span><?= /* @noEscape */ $_region ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape */ $_region ?>"
                        placeholder="<?= /* @noEscape */ $_region ?>"
                        class="validate-select region_id"
                        <?= /* @noEscape */ !$_displayAll ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $escaper->escapeHtml(__($_selectRegion)) ?></option>
                </select>
            </div>
        </div>

        <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($_vatidValidationClass) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>

        <?php $subscribedTitle = 'Would you like to join our Monthly Mailing list for discounts and promotions?';?>
        <div class="field choice newsletter">
            <input type="checkbox"
                   name="is_subscribed"
                   title="<?= $block->escapeHtmlAttr(__($subscribedTitle)) ?>"
                   value="1"
                   id="is_subscribed"
                   <?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                   class="checkbox"/>
            <label for="is_subscribed" class="label">
                <span>
                    <?= $block->escapeHtml(__($subscribedTitle)) ?>
                </span>
            </label>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    disabled="disabled"
                    title="<?= $escaper->escapeHtmlAttr(__('Save Basic Details')) ?>">
                <span><?= $escaper->escapeHtml(__('Save Basic Details')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes() ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $_displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $viewModel->dataGetRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->dataGetCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php
    $scriptString = <<<script
        require(['jquery','Magento_Customer/js/customer-data','jquery/ui','mage/mage'], function($,customerData){
    script;
?>
<?php if ($formDisable == 1): ?>
    <?php
        $scriptString .= <<<script
            $(document).ready(function(){
                $("#form-validate :input").prop("disabled", true);
                setTimeout(function(){
                    $("#form-validate :input").prop("disabled", true);
                }, 5000);
            });
        script;
    ?>
<?php endif; ?>
<?php
    $scriptString .= <<<script
            $(document).ready(function(){
                var sections = ['customer'];
                customerData.reload(sections, true);
                jQuery("#form-validate #country").attr("disabled","true");
            });

            //right before the form submits, we re-enable the fields, to make them submit.
            $("#form-validate").submit(function( event ) {
                if($('#form-validate').valid()){
                    $("body").trigger('processStart');
                    $("#country").prop( "disabled", false );
                }
            });


            $("#country").change(function () {
                onCountryChange();
            });
        });
        function onCountryChange() {
            require(['jquery'], function($){
                var countryval = $('#country option:selected').val();
                if(countryval=='US'){
                    $('#region_id_label').children('span').html("$regionStateLabel");
                    $('#region_id').attr('placeholder',"$regionStateLabel");
                    $('.vat-tax-id').show();
                    $('.tin-number').show();
                    $('.tobacco-permit-number').show();
                }else{
                    $('#region_id_label').children('span').html("$regionProvinceLabel");
                    $('#region').attr('placeholder',"$regionProvinceLabel");
                    $('.vat-tax-id').hide();
                    $('#vat_tax_id').val('');
                    $('.tin-number').hide();
                    $('#tin_number').val('');
                    $('.tobacco-permit-number').hide();
                    $('#tobacco_permit_number').val('');
                }
            });
        }
    script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
