<?php if ($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs">
        <ul class="items">
            <?php $itemListElement = [];
                  $position = 1; ?>

            <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                 
                <?php $crumblabel = $block->escapeHtml($crumbInfo['label']); ?>
                <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                    <?php if ($crumbInfo['link']): ?>
                        <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>

                        <?php $itemListElement[] = ["@type" => "ListItem", "position" => $position, "name" =>$crumblabel, "item" => $crumbInfo['link']]; ?>
                    
                    <?php else: ?>
                        <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php $itemListElement[] = ["@type" => "ListItem", "position" => $position, "name" => $crumblabel]; ?>
                    <?php endif; ?>

                </li>
                <?php $position++; ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php     

          $itemListElement = json_encode($itemListElement);
    ?>
    <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": <?= $itemListElement ?>
        }
    </script>
<?php endif; ?>
