<?php
/**
 * @var $this \Avalara\Excise\Block\CustomerAddress
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "addressValidationModal": {
                "validationEnabled": <?= /* @noEscape */ (int)$block->isValidationEnabled() ?>,
                "hasChoice": <?= /* @noEscape */ $block->getChoice() ?>,
                "instructions": <?= /* @noEscape */ $block->getInstructions() ?>,
                "errorInstructions": <?= /* @noEscape */ $block->getErrorInstructions() ?>,
                "countriesEnabled": "<?= /* @noEscape */ $block->getCountriesEnabled() ?>"
            }
        }
    }
</script>
<script>
    require([
        'mage/url'
    ], function(url) {
        return url.setBaseUrl('<?= /* @noEscape */ $block->getUrl();?>');
    })
</script>
<script type="text/javascript">
    window.avalaraStoreCode = "<?= /* @noEscape */ $block->getStoreCode() ?>";
</script>
