<?php //phpcs:disable ?>
<?php
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php
    $showCart = true;
    $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
    $showCart = $_helperB2b->isCustomerLoggedIn();
    $docdata = $_helperB2b->getDocMessageData();
    $is_document_upload = $_helperB2b->getDocuments();
    $IsFinanceVerified=$_helperB2b->getIsFinanceVerified();

?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ?
                         '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                             class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                <?php
                                /*
                                Here we removed the condition of the Document verified
                                ( $is_document_upload $doc_expired) and uploaded($IsFinanceVerified)
                                */
                                ?>
                                <?php if ($IsFinanceVerified == 1): ?>
                                    <?= $block->getProductPriceHtml($_item, $type) ?>

                                    <?= $block->getProductDetailsHtml($_item) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form" data-product-sku="
                                                        <?= $block->escapeHtml($_item->getSku()) ?>"
                                                        action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                         method="post">
                                                            <input type="hidden" name="product" value="
                                                            <?=
                                                            $block->escapeHtmlAttr($postParams['data']['product']) ?>
                                                            ">
                                                            <input type="hidden"
                                                            name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                             value="
                                            <?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>
                                                             ">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <?php
                                                            ?>
                                                            <?php if ($IsFinanceVerified == 1): ?>
                                                        <?php else: ?>
                                                         <!-- start view details btn -->
                                                            <div class="actions-primary">
                                                                    <div class="logged-in-action">
                                                                        <a href="
                                                        <?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                        ><?= $block->escapeHtml(__('View Details')) ?></a>
                                                                    </div>
                                                            </div>
                                                        <?php endif; ?>
                                                        <!-- end -->
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_item->isAvailable()): ?>
                                                            <div
                                                            class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else: ?>
                                                            <div
                                                            class="stock unavailable">
                                                            <span>
                                                                <?= $block->escapeHtml(__('Out of stock')) ?>
                                                            </span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <?php elseif (!$showCart): ?>
                                                <div class="actions-primary">
                                                    <div class="logged-in-action">
                                                        <a
                                            href="<?= $block->escapeUrl($block->getUrl('customer/account/login'))
                                                         ?>">
                                                            <?= $block->escapeHtml(__('Signin / Register')) ?>
                                                        </a>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if ($block->getBlockHtml('formkey')): ?>
    <script>
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
    <?php endif;?>
<?php endif;?>
