<?php //phpcs:disable ?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
/** LayeredNavigation Block State
 */
$stateBlock = $block->getLayout()->createBlock(\Magento\LayeredNavigation\Block\Navigation\State::class);
?>
<?php /* get document boolean value using helper [vy]*/?>

<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
$IsFinanceVerified = $_helperB2b->getIsFinanceVerified();
?>
<?php ?>
    <div class="cate-filter"><a href="javascript:void(0)" class="filter_button" id="is_filter">
    <span class="filter-text-span"><?= $block->escapeHtml(__("Hide Filter")) ?></span></a></div>
<?php ?>
<?php if ($block->canShowBlock()): ?>    
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <?php $_filters = $stateBlock->getActiveFilters() ?>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-role="title">
            <strong role="heading" aria-level="2" data-role="title"
                    data-count="<?= /* @noEscape */ count($_filters) ?>"><?= $block->escapeHtml(__('Show Filters')) ?>
            </strong>
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
                       class="action clear filter-clear">
                       <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if (!$wrapOptions): ?>
                    <strong role="heading" aria-level="2"
                            class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Filters')) ?>
                    </strong>
                    <div class="filter-options" id="narrow-by-list">
                        <?php if (!empty($_filters)): ?>
                        <div class="filter-current active">
                            <strong class="block-subtitle filter-current-subtitle"
                                    role="heading"
                                    aria-level="2"
                                    data-role="title"
                                    data-count="<?= /* @noEscape */ count($_filters) ?>">
                                    <?= $stateBlock->escapeHtml(__('Now Shopping by')) ?>
                            </strong>
                            <ol class="items">
                                <?php foreach ($_filters as $_filter): ?>
                                    <li class="item">
                                        <span class="filter-label">
                                              <?= $stateBlock->escapeHtml(__($_filter->getName())) ?>
                                        </span>
                                        <span class="filter-value">
                                              <?=$stateBlock->escapeHtml($stateBlock->stripTags($_filter->getLabel()))?>
                                        </span>
                                        <?php
                                        $clearLinkUrl = $_filter->getClearLinkUrl();
                                        $currentFilterName = $stateBlock
                                        ->escapeHtmlAttr(__($_filter->getName()) . " " . $stateBlock
                                            ->stripTags($_filter->getLabel()));
                                        if ($clearLinkUrl):
                                            ?>
                                            <a class="action previous"
                                            href="<?= $stateBlock->escapeUrl($_filter->getRemoveUrl()) ?>"
                                            title="<?= $stateBlock->escapeHtmlAttr(__('Previous')) ?>">
                                                <span><?= $stateBlock->escapeHtml(__('Previous')) ?></span>
                                            </a>
                                            <a class="action remove" title="<?= $stateBlock->escapeHtmlAttr($_filter
                                                ->getFilter()->getClearLinkText()) ?>"
                                            href="<?= $stateBlock->escapeUrl($clearLinkUrl) ?>">
                                                <span><?= $stateBlock->escapeHtml($_filter
                                                    ->getFilter()->getClearLinkText()) ?>
                                                </span>
                                            </a>
                                        <?php else: ?>
                                            <a class="action remove"
                                               href="<?= $stateBlock->escapeUrl($_filter->getRemoveUrl()) ?>"
                                            title="<?= /* @noEscape */ $stateBlock
                                            ->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName ?>">
                                                <span><?= $stateBlock->escapeHtml(__('Remove This Item')) ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ol>
                        </div>
                        
                            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                                <div class="block-actions filter-actions">
                                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
                                        class="action clear filter-clear">
                                        <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>

                    <?php endif; ?>
                    
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <?php /* start Check the document is verified or not [vy]*/?>
                        <?php if ($filter->getName() != "Price"): ?>
                            <div  class="filter-options-details">
                                    <div role="heading" aria-level="3" class="filter-options-title">
                                        <?= $block->escapeHtml(__($filter->getName())) ?>    
                                    </div>
                                    <div class="filter-options-content">
                                        <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?> 
                                    </div>
                            </div>
                        <?php else: ?>
                            <?php if ($IsFinanceVerified == 1): ?>
                                <div  class="filter-options-details">
                                    <div role="heading" aria-level="3" class="filter-options-title">
                                        <?= $block->escapeHtml(__($filter->getName())) ?>    
                                    </div>
                                    <div class="filter-options-content">
                                        <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?>     
                                    </div>
                                </div>
                            <?php endif; ?>   
                            <?php /* end [vy]*/?>

                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>    
