<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<div class="product alert <?= $block->getHtmlClass() ?>">
    <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
       title="<?= $block->escapeHtml(__('Notify Me')) ?>" class="action alert">
        <?= $block->escapeHtml(__('Notify Me')) ?>
    </a>
</div>
