<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null);

?>
<div class="post-view">
    <div class="post-holder post-holder-<?= (int)$_post->getId() ?>">
        <div class="post-content">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <?php
                $featuredImgAlt = $_post->getData('featured_img_alt');
                if (!$featuredImgAlt) {
                    $featuredImgAlt = $_postName;
                }
                ?>
                <div class="post-ftimg-hld">
                    <img src="<?= $block->escapeUrl($featuredImage) ?>"
                         alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                </div>
            <?php } ?>
            <div class="post-description clearfix">
                <h1 class="post-title title"><?= __($_postName); ?></h1>
                <?= $block->getInfoHtml() ?>
                <?php if($_post->getShortContent() != '') : ?>
                    <div class="post-short-content"><?= __($_post->getShortFilteredContent(null, '...')); ?></div>
                <?php endif; ?>
                <div class="post-text-hld">
                    <?= /*@noEscape*/ $block->getContent() ?>
                    <div class="clear clearfix"></div>
                </div>
            </div>
        </div>

        <div class="post-bottom">
            <?= $block->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>