<!-- <fieldset class="fieldset admin__fieldset"> -->
    <div class="admin__field field field-purchase-order" style="margin-top: 20px">
        <label class="label admin__field-label" for="purchase_order"><span>Purchase Order</span></label>
        <div class="admin__field-control control">
            <input id="purchase_order" name="order[purchase_order]" class="admin__control-text input-text admin__control-text" type="text" style="width: 50%" value="<?= $block->escapeHtml($block->getPurchaseOrder()) ?>">
        </div>
    </div>
<!-- </fieldset> -->