<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

/** @var \Magedelight\Subscribenow\Block\Adminhtml\ProductSubscribers\View\Tab\RelatedOrders $block */
$blockGrid = $block->getBlockGrid();

/** @var \Magedelight\Subscribenow\Block\Adminhtml\ProductSubscribers\View\Tab\Grid\RelatedOrders $blockGrid */
$gridJsObjectName = $blockGrid->getJsObjectName();
?>

<?php echo $block->getGridHtml() ?>

<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>

