<?php

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <?php /* Adding the Country code customization*/  ?>
    <div class="control">
        <input type="text"
               name="telephone"
               id="telephone"
               data-validate="{'phone': true}"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               placeholder="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $block->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               ) ?>"
        >
    </div>
</div>
