<?php
$customerid = $block->getCustomerId();
$docdata = $block->getDocumentCollection($customerid);
$data = $docdata->getData();
$dataSize = count($data);
$mediaUrl = $block->getMediaUrl();
$mediaUrl = $mediaUrl."myDocument/";
$is_delete = [];
$pdfImg = $block->getViewFileUrl('images/pdf.svg');
$docApprove = $block->getViewFileUrl('images/doc_approved.png');
foreach ($data as $val) {
    $is_delete[] = $val['is_delete'];
}
$count = 0;
$uploaderType = [
    'FEIN',
    'Sales Tax/Resale License',
    'State Tobacco License',
    'Unified Resale Certificate'
];
$customResultUrl = $block->getUrl('mydocument/customer/result');
$deleteDocumentUrl = $block->getUrl('mydocument/customer/deletedocument');
$updateDocumentUrl = $block->getUrl('mydocument/customer/updatedocument');
$today = date("Y-m-d");
?>
<div class="document-title">
    <span class="title">
        <?= $block->escapeHtml(__('My Documents')); ?>
    </span>
    <span class="note">
        <?= $block->escapeHtml(__('(File type supported are JPG, PNG and PDF)')); ?>
    </span>
</div>
<?php if (!empty($data)):

    /*for sorting the array in proper order start[BS]*/
    $static = [];
    $add_more = [];
    foreach ($data as $val) {
        if (in_array($val['document_name'], $uploaderType)) {
            $static[] = $val;
        }
        if ($val['is_add_more_form'] == 1) {
            $add_more[] = $val;
        }
    }

    $array=[];
    if (!empty($static)) {
        foreach ($static as $key => $row) {
            $array[$key] = $row['document_name'];
        
        }
        array_multisort($array, SORT_ASC, $static);
    }
    $newData = array_merge($static, $add_more);
    /*for sorting the array in proper order end[BS]*/?>
    
<div class="my_document">
    <form id="updatedocument"
        class="updatedocument"
        accept-charset="utf-8"
        enctype="multipart/form-data"
        data-mage-init='{"validation":{}}'
        method="post">

    <div class="updated-container">

        <?php foreach ($newData as $val): ?>
            <?php if ($val['is_add_more_form'] == 0): ?>

                <?php if ($val['is_delete'] == 0): ?>
                    <?php $expiry_date = $val['expiry_date']; ?>
                    <?php if (($val['status'] == 0 && $val['message'] != null) ||
                    (($expiry_date <= $today && $expiry_date != ""))): ?>
                        <?php $rejectedClass = "rejected"; ?>
                    <?php else: ?>
                        <?php $rejectedClass = ""; ?>
                    <?php endif; ?>
                    <?php $fileName = $mediaUrl.$val['filename']; ?>
                    <div class="document <?= $block->escapeHtml($rejectedClass); ?>" for="document uploader">
                        <?php
                            $checkext = $block->checkExtension($fileName);
                            $extension = $checkext['extension'];
                        ?>
                        <label><?= $block->escapeHtml(__($val['document_name'])); ?></label>
                        <div class="input-file">
                            <?php if ($extension == "pdf"): ?>
                                <img src="<?= $block->escapeUrl($pdfImg); ?>" height="34" width="43"
                                class="pdf-image" alt="pdf documents" />
                            <?php else: ?>
                                <img src="<?= $block->escapeUrl($fileName); ?>" height="170" width="170" />
                            <?php endif; ?>
                            <div class="doc-actions">
                                <?php if ($val['status'] == 0
                                &&
                                $val['message'] != null
                                ||
                                (($expiry_date <= $today && $expiry_date != ""))): ?>
                                    <a  class="view-doc-link" href="<?= $block->escapeUrl($fileName); ?>"
                                        target="_blank"></a>
                                    <a  class="deletedocument" name="deletedocument" href="#"
                                        id="<?= $block->escapeHtml($val['mydocument_id']); ?>"></a>
                                <?php else: ?>
                                    <a  class="view-doc-link" href="<?= $block->escapeUrl($fileName); ?>"
                                        target="_blank"></a>
                                <?php endif; ?>
                            </div>
                            <?php if ($val['status'] != 0 && $val['message'] == null): ?>
                            <span class="approved">
                                <img src="<?= $block->escapeUrl($docApprove); ?>"
                                    alt="approved_union"
                                    width="60"
                                    height="60"
                                    loading="lazy" />
                            </span>
                            <?php endif; ?>
                        </div>
                        <div class="doc-name">
                            <span><?= $block->escapeHtml($val['filename']); ?></span>
                            <a  href="<?= $block->escapeUrl($fileName); ?>"
                                target="_blank" download class="download-doc"></a>
                        </div>
                        <?php if (isset($val['expiry_date'])): ?>
                            <div class="field">
                                <div class="value date">
                                    <?= $block->escapeHtml(__('Expiry Date: ') . $val['expiry_date']); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if ($val['status'] == 0 && $val['message'] != null): ?>
                            <div class="doc-tooltip">
                                <span class="tooltip-toggle">
                                    <?= $block->escapeHtml(__('PLEASE CHECK THE DETAILS')); ?>
                                </span>
                                <span class="tooltip-content">
                                    <?= $block->escapeHtml($val['message']); ?>
                                </span>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php else: ?>
                    <div class="upload" for="document uploader">
                        <label><?= $block->escapeHtml(__($val['document_name'])); ?></label>
                        <div class="input-file" id="input-updatefile-<?= $block->escapeHtml($val['mydocument_id']);?>">
                            <input type="hidden" name="documentid[]"
                            value="<?= $block->escapeHtml($val['mydocument_id']); ?>" />
                            <input type="file" id="updatefile_<?= $block->escapeHtml($val['mydocument_id']);?>"
                            class="upload-filename"
                            name="updatefile<?= $block->escapeHtml($val['mydocument_id']);?>"
                            data-validate="{required:true}"/>
                            <span class="input-note">
                                <?= $block->escapeHtml(__('(Only one document can be uploaded)')); ?>
                            </span>
                            <span id="image-error-message<?= $block->escapeHtml($val['mydocument_id']);?>"
                                style="color:red;"></span>
                            <!-- bv_vv; date:04-02-2022; File Preview Start; -->
                            <img class="previewimage-filename<?= $block->escapeHtml($val['mydocument_id']);?>"
                            height="170" width="170"
                            src="" title="" style="display:none;"/>
                            <div class="doc-actions"
                            id="doc-actions-filename<?= $block->escapeHtml($val['mydocument_id']);?>"
                            style="display:none;">
                                <a class="view-doc-link"
                                id="view-doc-link-filename<?= $block->escapeHtml($val['mydocument_id']);?>"
                                href="" target="_blank"></a>
                                <a class="deletedocument-preview deletedocument"
                                id="deletedocument-filename<?= $block->escapeHtml($val['mydocument_id']);?>"></a>
                            </div>
                            <!-- bv_vv; date:04-02-2022; File Preview End; -->
                        </div>  
                        <div class="doc_name" for="document name" style="display:none !important;">
                            <label><?= $block->escapeHtml(__('Document Name')); ?></label>
                            <input type="text" id="name-<?= $block->escapeHtml($val['mydocument_id']);?>"
                            name="name<?= $block->escapeHtml($val['mydocument_id']);?>"
                            data-validate="{required:true}"
                            value="<?= $block->escapeHtml($val['document_name']); ?>" readonly/>
                        </div>
                        <div class="set_expiry" for="document expiry data" style="display:none" >
                            <label><?= $block->escapeHtml(__('Set a Specific Expiry date')); ?></label>
                            <input type="checkbox" id="toggle<?= $block->escapeHtml($val['mydocument_id']);?>"
                            name="set_expiry[]" class="cmn-toggle cmn-toggle-round" />
                            <span class="slider round"></span>
                            <div class="expiry_dates expiry_dates<?= $block->escapeHtml($val['mydocument_id']);?>"
                                for="document expiry data" style="display:none">
                                <label><?= $block->escapeHtml(__('Set Expiry Date')); ?></label>
                                <!-- old date[BS] -->
                                <input type="text" placeholder="Expiry Date"
                                name="expiry_date<?= $block->escapeHtml($val['mydocument_id']);?>"
                                id="expiry_date<?= $block->escapeHtml($val['mydocument_id']);?>"
                                data-validate="{required:true}"
                                value="" readonly/>
                            </div>
                        </div>
                        <input type="hidden"
                        id="is_add_more_form<?= $block->escapeHtml($val['mydocument_id']);?>"
                        name="is_add_more_form[]" value="0"/>
                    </div>
                <?php endif; ?>
            <?php else: ?>

                <?php if ($count == 0): ?>
                <span class="document-title add-more-field">
                    <span class="field">
                   <input type="checkbox" class="checkbox" checked disabled>
                   <label class="label" style="width:100%">
                            <span>
                                <?= $block->escapeHtml(__('Do you want to upload other document?')); ?>
                            </span>
                    </label>
                </span>
                    <span class="note">
                        <?= $block->escapeHtml(__('(File type supported are JPG, PNG and PDF)')); ?>
                    </span>

                </span>
           <?php endif;?>

                <?php if ($val['is_add_more_form'] == 1):?>
                    <?php if ($val['is_delete'] == 0): ?>
                        <?php
                        if (($val['status'] == 0 && $val['message'] != null) ||
                        (($val['expiry_date'] <= $today && $val['expiry_date'] != ""))):?>
                            <?php $rejectedClass = "rejected"; ?>
                        <?php else: ?>
                            <?php $rejectedClass = ""; ?>
                        <?php endif;?>
                        <div class="document <?= /* @noEscape */ $rejectedClass; ?>" for="document uploader">
                            <?php
                            $fileName = $mediaUrl.$val['filename'];
                            $checkext = $block->checkExtension($fileName);
                            $extension = $checkext['extension'];
                            ?>
                            <div class="input-file">
                                <?php if ($extension == "pdf"): ?>
                                    <img src="<?= $block->escapeUrl($pdfImg); ?>" height="34" width="43"
                                    class="pdf-image" alt="pdf documents" />
                                <?php else: ?>
                                    <img src="<?= $block->escapeUrl($fileName); ?>" height="170" width="170" />
                                <?php endif; ?>
                                <div class="doc-actions">
                                    <?php if ($val['status'] == 0
                                    &&
                                    $val['message'] != null
                                    ||
                                    (($val['expiry_date'] <= $today && $val['expiry_date'] != ""))): ?>
                                        <a  class="view-doc-link" href="<?= $block->escapeUrl($fileName); ?>"
                                            target="_blank"></a>
                                        <a  class="deletedocument" name="deletedocument" href="#"
                                            id="<?= $block->escapeHtml($val['mydocument_id']); ?>"></a>
                                    <?php else: ?>
                                        <a  class="view-doc-link" href="<?= $block->escapeUrl($fileName); ?>"
                                            target="_blank"></a>
                                    <?php endif; ?>
                                </div>
                                <?php if ($val['status'] != 0 && $val['message'] == null): ?>
                                <span class="approved">
                                    <img src="<?= $block->escapeUrl($docApprove); ?>"
                                    alt="approved_union"
                                    width="60"
                                    height="60"
                                    loading="lazy" />
                                </span>
                                <?php endif; ?>
                            </div>
                            <div class="doc-name">
                                <span><?= $block->escapeHtml($val['filename']); ?></span>
                                <a  href="<?= $block->escapeUrl($fileName); ?>"
                                    target="_blank" download class="download-doc"></a>
                            </div>
                            <div class="field">
                                <label><?= $block->escapeHtml(__("Document Name"));  ?></label>
                                <div class="value">
                                    <?= $block->escapeHtml($val['document_name']); ?>
                                </div>
                            </div>
                                <?php if (isset($val['expiry_date'])): ?>
                                <div class="field">
                                    <div class="value date">
                                        <?= $block->escapeHtml(__('Expiry Date: ') . $val['expiry_date']); ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                                <?php if ($val['status'] == 0 && $val['message'] != null): ?>
                                <div class="doc-tooltip">
                                    <span class="tooltip-toggle">
                                        <?= $block->escapeHtml(__('PLEASE CHECK THE DETAILS')); ?>
                                    </span>
                                    <span class="tooltip-content">
                                        <?= $block->escapeHtml($val['message']); ?>
                                    </span>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php else: ?>
                    <div class="upload" for="document uploader">
                        <div class="input-file" id="input-updatefile-<?= $block->escapeHtml($val['mydocument_id']);?>">
                            <input type="hidden" name="documentid[]"
                            value="<?= $block->escapeHtml($val['mydocument_id']); ?>" />
                            <input type="file" id="updatefile_<?= $block->escapeHtml($val['mydocument_id']);?>"
                            class="upload-filename"
                            name="updatefile<?= $block->escapeHtml($val['mydocument_id']);?>"
                            data-validate="{required:true}"/>
                            <span class="input-note">
                                <?= $block->escapeHtml(__('(Only one document can be uploaded)')); ?>
                            </span>
                            <span id="image-error-message<?= $block->escapeHtml($val['mydocument_id']);?>"
                                style="color:red;"></span>
                            <img class="previewimage-filename<?= $block->escapeHtml($val['mydocument_id']);?>"
                            height="170" width="170" src="" title="" style="display:none;"/>
                            <div class="doc-actions"
                                id="doc-actions-filename<?= $block->escapeHtml($val['mydocument_id']);?>"
                                style="display:none;">
                                <a class="view-doc-link"
                                id="view-doc-link-filename<?= $block->escapeHtml($val['mydocument_id']);?>"
                                href="" target="_blank"></a>
                                <a class="deletedocument-preview deletedocument"
                                id="deletedocument-filename<?= $block->escapeHtml($val['mydocument_id']);?>"></a>
                            </div>
                        </div>
                        <div class="doc_name" for="document name">
                            <label><?= $block->escapeHtml(__('Document Name')); ?></label>
                            <input type="text"
                            id="name-<?= $block->escapeHtml($val['mydocument_id']);?>"
                            name="name<?= $block->escapeHtml($val['mydocument_id']);?>"
                            data-validate="{required:true}"
                            value="<?= $block->escapeHtml($val['document_name']); ?>" />
                        </div>
                        <div class="set_expiry" for="document expiry data" style="display:none" >
                            <label><?= $block->escapeHtml(__('Set a Specific Expiry date')); ?></label>
                            <input type="checkbox" id="toggle<?= $block->escapeHtml($val['mydocument_id']);?>"
                            name="set_expiry[]" class="cmn-toggle cmn-toggle-round" />
                            <span class="slider round"></span>
                            <div class="expiry_dates expiry_dates<?= $block->escapeHtml($val['mydocument_id']);?>"
                                for="document expiry data" style="display:none">
                                <label><?= $block->escapeHtml(__('Set Expiry Date')); ?></label>
                                <!-- old date[BS] -->
                                <input type="text"
                                placeholder="Expiry Date"
                                name="expiry_date<?= $block->escapeHtml($val['mydocument_id']);?>"
                                id="expiry_date<?= $block->escapeHtml($val['mydocument_id']);?>"
                                data-validate="{required:true}" 
                                value="" readonly/>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                <?php endif; ?>
                <?php $count++; ?>
            <?php endif; ?>
        <?php endforeach; ?>
       </div>

        <?php if (in_array(1, $is_delete)): ?>
            <button type="submit" id="updatebtnsave" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')); ?></span>
            </button>
        <?php endif; ?>
    </form>
</div>
<?php endif; ?>
<?php
$doc_name = [];
foreach ($data as $val) {
    $doc_name[] = $val['document_name'];
}
?>
<?php if (empty($data)): ?>
<div class="my_document">
    <form name="usaform" id="usaform"
        class="usaform" 
        accept-charset="utf-8"
        enctype="multipart/form-data"
        autocomplete="off" data-mage-init='{"validation":{}}'>
        <input type="hidden" id="is_customerfrom_usa" name="is_customerfrom_usa[]" value="1"/>
        <!-- FILE UPLOADER START FOR FEIN-->
        <div class="upload-container">
            <?php foreach ($uploaderType as $key => $value): ?>
                <?php if (!in_array($value, $doc_name)): ?>
                    <?php $counter = $key + 1;?>
            <div class="upload" for="document uploader">
                <label><?= $block->escapeHtml(__($value)); ?></label>
                <div class="input-file" id="input-filename<?= $block->escapeHtml($counter);?>">
                    <input type="file"
                    id="filename<?= $block->escapeHtml($counter); ?>"
                    class="upload-filename"
                    name="filename<?= $block->escapeHtml($counter); ?>"
                    />
                    <span class="input-note">
                        <?= $block->escapeHtml(__('(Only one document can be uploaded)')); ?>
                    </span>
                    <span id="image-error-message<?= $block->escapeHtml($counter); ?>" style="color:red;"></span>
                    <!-- bv_vv; date:04-02-2022; File Preview Start; -->
                    <img class="previewimage-filename<?= $block->escapeHtml($counter); ?>"
                    height="170" width="170" src="" title="" style="display:none;"/>
                    <div class="doc-actions" id="doc-actions-filename<?= $block->escapeHtml($counter); ?>"
                        style="display:none;">
                        <a class="view-doc-link" id="view-doc-link-filename<?= $block->escapeHtml($counter); ?>"
                            href="" target="_blank"></a>
                        <a class="deletedocument-preview deletedocument"
                        id="deletedocument-filename<?= $block->escapeHtml($counter); ?>"></a>
                    </div>
                    <!-- bv_vv; date:04-02-2022; File Preview End; -->
                </div>
                <div class="doc_name" for="document name" style="display:none !important;">
                    <label><?= $block->escapeHtml(__('Document Name')); ?></label>
                    <input type="text"
                    id="name-<?= $block->escapeHtml($counter); ?>"
                    name="name<?= $block->escapeHtml($counter); ?>"
                    data-validate="{required:true}"
                    value="<?= $block->escapeHtml($value); ?>" readonly/>
                </div>
                <div class="set_expiry" for="document expiry data" style="display:none" >
                    <label><?= $block->escapeHtml(__('Set a Specific Expiry date')); ?></label>
                    <input type="checkbox" id="toggle<?= $block->escapeHtml($counter); ?>"
                    name="set_expiry[]" class="cmn-toggle cmn-toggle-round" />
                    <span class="slider round"></span>
                    <div class="expiry_dates expiry_dates<?= $block->escapeHtml($counter); ?>"
                        for="document expiry data" style="display:none">
                        <label><?= $block->escapeHtml(__('Set Expiry Date')); ?></label>
                        <input type="text"
                        placeholder="Expiry Date"
                        name="expiry_date<?= $block->escapeHtml($counter); ?>"
                        id="expiry_date<?= $block->escapeHtml($counter); ?>"
                        data-validate="{required:true}" readonly/>
                    </div>
                </div>
                <input type="hidden"
                id="is_add_more_form<?= $block->escapeHtml($counter); ?>"
                name="is_add_more_form[]"
                value="0"/>
            </div>
            <?php endif; ?>
            <?php endforeach; ?>
            <!-- FOR ADD MORE START -->
            <div class="upload" for="document uploader">
                <span class="image-error-message" style="color:red;"></span>
                <div class="doc_name" for="document name"></div>
                <div class="set_expiry" for="document expiry data"></div>
                <div class="expiry_dates" for="document expiry data"></div>
            </div>
            <!-- FOR ADD MORE END -->
        </div>
        <?php if (empty($data)): ?>
            <div class="document-title add-more-field">
                <div class="field">
                    <input type="checkbox" class="checkbox">
                    <label class="label">
                        <span>
                            <?= $block->escapeHtml(__('Do you want to upload other document?')); ?>
                        </span>
                    </label>
                </div>
                <span class="note" style="display: none;">
                    <?= $block->escapeHtml(__('(File type supported are JPG, PNG and PDF)')); ?>
                </span>
            </div>
            <div class="upload-container add-more-container" style="display:none;">
                <div class="add-more-cont">
                    <a id="add_more"><?= $block->escapeHtml(__('Add More Document')); ?></a>
                </div>
            </div>
        <?php endif; ?>
        <button type="submit" id="btnsave" class="action submit primary" style="display:none;">
            <span><?= $block->escapeHtml(__('Submit')); ?></span>
        </button>
    </form>
</div>
<?php endif; ?>
<div id="popup-modal"  style="display:none">
    <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/success_union.svg')); ?>"
    alt="success_union" width="60" height="60" loading="lazy" />
    <h1 class="success_msg"><?= $block->escapeHtml(__('DOCUMENTS ARE UPLOADED SUCCESSFULLY')); ?></h1>
    <h5><?= $block->escapeHtml(__('Once it is approved by Admin, Product price would be visible to you.')); ?></h5>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Alfakher_MyDocument/js/documentforusa": {
            "pdfImg": "<?= $block->escapeUrl($pdfImg); ?>",
            "inputNote": "<?= $block->escapeHtml(__('(Only one document can be uploaded)')); ?>",
            "customResultUrl": "<?= $block->escapeUrl($customResultUrl); ?>",
            "deleteDocumentUrl": "<?= $block->escapeUrl($deleteDocumentUrl); ?>",
            "updateDocumentUrl": "<?= $block->escapeUrl($updateDocumentUrl); ?>"   
        }
    }
}
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "usaform"
            }
        }
    }
</script>
<script>
           require(['jquery', 'jquery/ui'], function($){
            $(document).on( 'click', '#btnsave', function () {

            if($("#filename1").val()==""){
                $("input[name=name1]").val('');
            }
            if($("#filename2").val()==""){
                $("input[name=name2]").val('');
            }
            if($("#filename3").val()==""){
                $("input[name=name3]").val('');
            }
            if($("#filename4").val()==""){
                $("input[name=name4]").val('');
            }
  });
 });

</script>