<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper(Magento\Catalog\Helper\Output::class);
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
$IsFinanceVerified = $_helperB2b->getIsFinanceVerified();
$isCustomerLoggedIn = $_helperB2b->isCustomerLoggedIn();
?>

<?php if ($product->isSaleable()):?>
    <?php if (count($options)):?>
        <?php if ($isCustomerLoggedIn && $IsFinanceVerified) {?>
            <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "priceBundle": {
                        "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                        "controlContainer": ".field.option"
                    }
                }
            }
            </script>
        <?php } ?>
        <fieldset class="fieldset fieldset-bundle-options">
            <?= $block->getChildHtml('product_info_bundle_options_top') ?>
            <?php foreach ($options as $option): ?>
                <?php
                if (!$option->getSelections()) {
                    continue;
                } else {
                    echo $block->getOptionHtml($option);
                }
                ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?= $block->escapeHtml(__('No options of this product are available.')) ?></p>
    <?php endif; ?>
<?php endif;?>
