<?php
$viewModel = $block->getData('view_model');
$order = $block->getOrder();
$websiteId = $order->getStore()->getWebsiteId();

$moduleEnable = $viewModel->isModuleEnabled($websiteId);
$forInvoicedOrders = $viewModel->isAllowedForInvoicedOrder($websiteId);
$allowedPayment = $viewModel->getAllowedPayment($websiteId);
$recordCollection = $viewModel->getRecordCollection($order->getId());

$grandtotal = $order->getGrandtotal();
$totalPaid = $viewModel->getTotalPaidAmount($order->getId());

$totalDue = $grandtotal - $totalPaid;

$displaySection = 0;
$ordersPaymentMethod = $order->getPayment();

if (!$order->getInvoiceCollection()->count()) {
    $displaySection = 1;
} elseif ($forInvoicedOrders) {
    $displaySection = 1;
} else {
    $displaySection = 0;
}

?>
<?php if ($moduleEnable): ?>
<input type="hidden" name="af_grandtotal" id="af_grandtotal" value="<?= /* @noEscape */ $grandtotal ?>">
<input type="hidden" name="af_totalpaid" id="af_totalpaid" value="<?= /* @noEscape */ $totalPaid ?>">
<input type="hidden" name="af_totaldue" id="af_totaldue"
    value="<?= /* @noEscape */ $viewModel->getRoundDue($totalDue) ?>">

<section id="" class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title">Offline Payment Records</span>
        <div class="actions"></div>
    </div>
    <div id="" class="admin__page-section-content">
        <?php if ($displaySection && $ordersPaymentMethod->getMethodInstance()->getCode() == $allowedPayment): ?>
        <fieldset class="fieldset admin__fieldset">
            <div class="admin__field field">
                <label class="label admin__field-label">
                    <span>Payment Type</span>
                </label>
                <div class="admin__field-control control">
                    <select name="offline_payment_type" id="offline_payment_type"
                    class="required-entry required-entry _required select admin__control-select">
                        <option value="Net 15">Net 15</option>
                        <option value="Net 30">Net 30</option>
                        <option value="Paypal">Paypal</option>
                        <option value="Wire Transfer">Wire Transfer</option>
                        <option value="ACH">ACH</option>
                    </select>
                </div>
            </div>
        </fieldset>
        <div>
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary">
                    <tbody>
                        <tr>
                            <td>
                                <div class="admin__field field">
                                    <label class="label admin__field-label">
                                        <span>Transaction Number</span>
                                    </label>
                                    <div class="admin__field-control control">
                                        <input name="offline_transaction_number"
                                            id="offline_transaction_number"
                                            class="admin__control-text input-text admin__control-text"
                                            type="text" placeholder="Transaction Number">
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="admin__field field required _required">
                                    <label class="label admin__field-label">
                                        <span>Amount Paid</span>
                                    </label>
                                    <div class="admin__field-control control">
                                        <input name="offline_amount_paid"
                                            id="offline_amount_paid"
                                            class="admin__control-text input-text admin__control-text"
                                            type="text" placeholder="Amount Paid"
                                            oninput="this.value = 
                                            this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
                                        <label for="offline_amount_paid" generated="true"
                                            class="mage-error" id="offline_amount_paid-error"
                                            style="display: none;">This is a required field.</label>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="admin__field field required _required">
                                    <label class="label admin__field-label">
                                        <span>Date</span>
                                    </label>
                                    <div class="admin__field-control control">
                                        <input name="offline_transaction_date"
                                            id="offline_transaction_date"
                                            class="admin__control-text input-text admin__control-text"
                                            type="text" placeholder="Date (yy-mm-dd)" style="width: 100%">
                                        <label for="offline_transaction_date" generated="true"
                                            class="mage-error" id="offline_transaction_date-error"
                                            style="display: none;">This is a required field.</label>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td style="border-bottom: unset; padding-left: unset;">
                                <button type="button"
                                    class="action-default scalable custom-button primary"
                                    id="submit_offline_payment">Submit</button>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <?php endif; ?>

        <?php /*
        temp removed the condition
        $recordCollection->count()
        */ ?>
        <div>
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-tables">
                    <thead>
                        <tr class="headings">
                            <th><span>#</span></th>
                            <th><span>Payment Type</span></th>
                            <th><span>Transaction Number</span></th>
                            <th><span>Amount Paid</span></th>
                            <th><span>Date</span></th>
                            <th><span>Action</span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($recordCollection->count()): ?>
                            <?php foreach ($recordCollection as $key => $value): ?>
                                <tr>
                                    <td><?= /* @noEscape */ $value->getId() ?></td>
                                    <td><?= /* @noEscape */ $value->getpaymentType() ?></td>
                                    <td><?= /* @noEscape */ $value->getTransactionNumber() ?></td>
                                    <td><?= /* @noEscape */ $order->formatPrice($value->getAmountPaid()) ?></td>
                                    <td><?= /* @noEscape */ $value->getTransactionDate() ?></td>
                                    <td><button class="action-secondary af_payment_delete"
                                            type="button"
                                            data-record-id="<?= /* @noEscape */ $value->getId() ?>">Delete
                                        </button>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr class="even">
                                <td class="empty-text" colspan="100">No ordered items</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>Grand Total : <?= /* @noEscape */ $order->formatPrice($grandtotal) ?></td>
                            <td>Paid Amount : <?= /* @noEscape */ $order->formatPrice($totalPaid) ?></td>
                            <td>Amount Due : <?= /* @noEscape */ $order->formatPrice($viewModel
                                ->getTotalDue($totalDue)) ?></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>

<script>
    require(["jquery", 'Magento_Ui/js/modal/confirm', "mage/calendar"], function($, confirmation){
        var orderId = <?= /* @noEscape */ $order->getId() ?>;

        $("#offline_transaction_date").datepicker({
            showMonthAfterYear: false,
            dateFormat:'yy-mm-dd',
            changeMonth: true,
            changeYear: true,
            maxDate: 0,
        });

        $(document).on('click',"#submit_offline_payment", function () {
            var error = false;
            var paymentType = $("#offline_payment_type").val(); 
            var transactionNumber = $("input[name=offline_transaction_number]").val();
            var amountPaid = $("input[name=offline_amount_paid]").val();
            var paymentDate = $("input[name=offline_transaction_date]").val();
            var totalDueAmount = $("input[name=af_totaldue]").val();

            if (amountPaid == '') {
                $('input[name=offline_amount_paid]').addClass('mage-error');
                $("#offline_amount_paid-error").text("This is a required field.");
                $("#offline_amount_paid-error").css("display",'block');
                error = true;
            } else {
                if (parseFloat(amountPaid) > 0 && parseFloat(amountPaid) > parseFloat(totalDueAmount)) {
                    $('input[name=offline_amount_paid]').addClass('mage-error');
                    $("#offline_amount_paid-error").text("please enter smaller or equal amount of total due amount");
                    $("#offline_amount_paid-error").css("display",'block');
                    error = true;
                } else if (parseFloat(amountPaid) <= 0) {
                    $('input[name=offline_amount_paid]').addClass('mage-error');
                    $("#offline_amount_paid-error").text("please enter greater then zero amount");
                    $("#offline_amount_paid-error").css("display",'block');
                    error = true;
                } else {
                    $('input[name=offline_amount_paid]').removeClass('mage-error');
                    $("#offline_amount_paid-error").text("This is a required field.");
                    $("#offline_amount_paid-error").css("display",'none');
                }
            }

            if (paymentDate == '') {
                $('input[name=offline_transaction_date]').addClass('mage-error');
                $("#offline_transaction_date-error").css("display",'block');
                error = true;
            } else {
                $('input[name=offline_transaction_date]').removeClass('mage-error');
                $("#offline_transaction_date-error").css("display",'none');
            }
            
            if (error == false) {
                $.ajax({
                    url: "<?= /* @noEscape */ $block->getUrl('offlinepayments/Order/addpayment/') ?>",
                    showLoader: true,
                    type: 'POST',
                    data: {
                        order_id:orderId, 
                        paymentType: paymentType, 
                        transactionNumber: transactionNumber, 
                        amountPaid: amountPaid, 
                        paymentDate:paymentDate
                    },
                    success: function(response) {
                        if (response.status == 1) {    
                            location.reload(true);
                        }else{
                            alert(response.msg+" please try again!");
                        }
                    }
                });
            }
        });

        $(document).on("click", ".af_payment_delete", function () {
            var recordId = $(this).data("record-id");
        confirmation({
            title: $.mage.__('Delete Payment Record'),
            content: $.mage.__('This action will delete the payment record. Are you sure to perform this operation?'),
                actions: {
                    confirm: function(){
                        $.ajax({
                            url: "<?= /* @noEscape */ $block->getUrl('offlinepayments/Order/deletepayment/') ?>",
                            showLoader: true,
                            type: 'POST',
                            data: {
                                recordId:recordId
                            },
                            success: function(response) {
                                if (response.status == 1) {    
                                    location.reload(true);
                                }else{
                                    alert(response.msg+" please try again!");
                                }
                            }
                        });
                    }
                }
            });
        });
    });
</script>