<?php if ($_item = $block->getItem()): ?>
    <?php
        $viewModel = $block->getViewModel();
        $moduleEnable = $viewModel->isModuleEnabled($_item->getOrder()->getStore()->getStoreId());
    ?>
    <?php if ($moduleEnable): ?>
        <?php $validGrossMargin = $viewModel->validateGrossMargin($_item); ?>
        <?= /* @noEscape */ $_item->getGrossMargin() > 0 ? $_item->getGrossMargin()."%" : $validGrossMargin ."%" ?>
    <?php endif; ?>
<?php endif; ?>
