<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Sales\Block\Adminhtml\Order\Totals $block */
?>


<?php /* bv_op; date : 18-2-22; edit handling fee; Start */ ?>
<?php
$viewModel = $block->getData('view_model');
$order = $block->getOrder();
$websiteId = $order->getStore()->getWebsiteId();
$canShowFeeEdit = $viewModel->isModuleEnabled($websiteId);
?>
<?php /* bv_op; date : 18-2-22; edit handling fee; End */ ?>


<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer') ?>

    <?php if ($_totals): ?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else: ?>
                <tr class="col-<?= $block->escapeHtmlAttr($_code) ?>">
                    <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                        <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                    </td>
                    <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                        <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tfoot>
    <?php endif; ?>

    <?php $_totals = $block->getTotals('')?>
    <?php if ($_totals): ?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else: ?>
                    <tr class="col-<?= $block->escapeHtmlAttr($_code) ?>">
                        <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                            <?php if ($_total->getCode() == "shipping" && $canShowFeeEdit): ?>
                                <?php if ($_total->getStrong()): ?>
                                <strong><?= /* @noEscape */ __("Shipping") ?></strong>
                                <?php else: ?>
                                    <?= /* @noEscape */ __("Shipping") ?>
                                <?php endif?>
                            <?php else: ?>
                                <?php if ($_total->getStrong()): ?>
                                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                                <?php else: ?>
                                    <?= $block->escapeHtml($_total->getLabel()) ?>
                                <?php endif?>
                            <?php endif; ?>
                        </td>

                        <?php if ($_total->getStrong()): ?>
                            <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                                <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else: ?>
                            <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                                <span><?= /* @noEscape */ $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>
