<?php
declare(strict_types=1);
namespace Alfakher\SeoUrlPrefix\Model;

use Magento\CmsUrlRewrite\Model\CmsPageUrlPathGenerator;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use Magento\CmsUrlRewrite\Model\CmsPageUrlRewriteGenerator as CmsPageRewriteGenerator;
use Magento\Cms\Model\Page;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\Framework\App\Config\ScopeConfigInterface;

class CmsPageUrlRewriteGenerator extends CmsPageRewriteGenerator
{
    /**
     * Prefix stores
     */
    public const PREFIX_STORES = 'hookahshisha/prefix_add_seo/seo_stores';

    /**
     * Prefix store route
     */
    public const STORE_PREFIX = 'content/';
    
    /**
     * Entity type code
     */
    public const ENTITY_TYPE = 'cms-page';

    /**
     * @var UrlRewriteFactory
     */
    protected $urlRewriteFactory;

    /**
     * @var CmsPageUrlPathGenerator
     */
    protected $cmsPageUrlPathGenerator;

    /**
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var Page
     */
    protected $cmsPage;

    /**
     * @var ScopeConfigInterface
     */
    protected $scopeConfig;

    /**
     * @param UrlRewriteFactory $urlRewriteFactory
     * @param CmsPageUrlPathGenerator $cmsPageUrlPathGenerator
     * @param StoreManagerInterface $storeManager
     * @param ScopeConfigInterface $scopeConfig
     */
    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        CmsPageUrlPathGenerator $cmsPageUrlPathGenerator,
        StoreManagerInterface $storeManager,
        ScopeConfigInterface $scopeConfig
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->storeManager = $storeManager;
        $this->cmsPageUrlPathGenerator = $cmsPageUrlPathGenerator;
        $this->scopeConfig = $scopeConfig;
    }

    /**
     * Create url rewrite object
     *
     * @param int $storeId
     * @param int $redirectType
     * @return UrlRewrite
     */
    protected function createUrlRewrite($storeId, $redirectType = 0)
    {
        $storeDetails = $this->scopeConfig->getValue(self::PREFIX_STORES);
        $storeIds = $storeDetails ? explode(',', $storeDetails) : [];
    
        $prefix = in_array($storeId, $storeIds) ? self::STORE_PREFIX : '';
        
        return $this->urlRewriteFactory->create()->setStoreId($storeId)
            ->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($this->cmsPage->getId())
            ->setRequestPath($prefix . $this->cmsPage->getIdentifier())
            ->setTargetPath($this->cmsPageUrlPathGenerator->getCanonicalUrlPath($this->cmsPage))
            ->setIsAutogenerated(1)
            ->setRedirectType($redirectType);
    }
}
