<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

// @codingStandardsIgnoreFile
/** @var Magedelight\Subscribenow\Block\Checkout\Cart\Subscription\Summary $block */
?>

<?php if ($block->hasSubscriptionItem()): ?>
    <div id="block-shipping" class="block shipping" data-collapsible="true" role="tablist" data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
        <div class="title" data-role="title" aria-controls="product-summary" role="tab" aria-selected="false" aria-expanded="false" tabindex="0">
            <strong id="block-productsummary-heading" aria-level="2" role="heading"><?= /* @escapeNotVerified */ $block->escapeHtml($block->getSummaryTitle()); ?></strong>
        </div>
        <div id="plan-summary" class="shipping-form" data-bind="scope:'product-summary'" class="content" data-role="content" aria-labelledby="block-productsummary-heading">
            <p><?= $block->escapeHtml($block->getSummaryContent()); ?></p>
            <table id="product-summary-table">
                <tr>
                    <td class="title"><strong><?=  /* @escapeNotVerified */ __('Subscription Product(s)') ?></strong></td>
                </tr>
                <?php foreach ($this->getSubscriptionItems() as $name) : ?>
                    <tr>
                        <td class="col plan-title"><?= $block->escapeHtml($name); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
<?php endif; ?>