<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

// @codingStandardsIgnoreFile
/** @var \Magedelight\Subscribenow\Block\Adminhtml\ProductSubscribers\View\Tab\ProfileInfo\Details $block */
?>
<div class="admin__page-section-item-title">
    <span class="title">
        <?php echo $block->escapeHtml(__('Subscription Profile')) ?>
    </span>
</div>
<div class="admin__page-section-item-content">
    <table class="admin__table-secondary order-information-table">
        <tbody>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Profile Number') ?></th>
                <td><?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProfileId());?></td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Profile Status') ?></th>
                <td>
                    <span id="order_status">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscriptionStatus());?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                <td>
                    <?php if($block->getProductUrl() == '#') : ?>
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProductName()); ?>
                    <?php else : ?>
                    <a href="<?php echo $block->getProductUrl(); ?>" target="_blank" class="product-link">
                            <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProductName()); ?>
                        </a>
                    <?php endif; ?>

                    <?php if ($productOptions = $block->getProductOption()) { ?>
                        <dl class="item-options">
                            <?php foreach ($productOptions as $option) { ?>
                                <dt><strong><?= $option['label'] ?>:</strong></dt>
                                <dd><?= $option['value'] ?></dd>
                            <?php } ?>
                        </dl>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
                <td><?php /* @escapeNotVerified */ echo $block->getSubscription()->getProductSku(); ?></td>
            </tr>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Quantity') ?></th>
                <td>
                    <?php /* @escapeNotVerified */ 
                
                    if($block->isEditMode()): ?>
                        <input type="text"
                               name="qty"
                               value="<?php echo $block->escapeHtml($block->getQty()) ?>"
                               class="input-text required-entry validate-greater-than-zero validate-digits"
                               aria-required="true"
                        />
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getQty()) ?>
                    <?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>