<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>

<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                   name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
        <?php else:?>
            <select id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                    data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                    class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId())
                    ?> product bundle option bundle-option-select change-container-classname dropdown-stock"
                <?php if ($_option->getRequired()) { echo 'data-validate = {required:true}'; } ?>>
                <option value=""><?= $block->escapeHtml(__('Choose a selection...')) ?></option>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                        data-select-avai-qty="<?= /* @noEscape */
                        $_helperB2b->getStockQty($block->escapeHtmlAttr($_selection->getId()))?>"
                        <?php if ($block->isSelected($_selection)) { echo ' selected="selected"'; } ?>
                        <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>>
                        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <div id="option-tier-prices-<?= $block->escapeHtmlAttr($_option->getId()) ?>" class="option-tier-prices">
                <?php foreach ($_selections as $_selection): ?>
                    <div data-role="selection-tier-prices"
                         data-selection-id="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                         class="selection-tier-prices">
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if ($_helperB2b->isCustomerLoggedIn()):?>
        <div class="nested">
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <span><?= $block->escapeHtml(__('Quantity')) ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                           id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                           class="dropdown-qty input-text qty<?php if (!$_canChangeQty) { echo ' qty-disabled'; } ?>"
                           type="number"
                           min = "1"
                           name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                           data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                           value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"
                           onclick="this.select();"/>
                </div>
                 <span id="select-stock-msg" style="color: red;"></span>
            </div>
        </div>
    <?php endif; ?>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        jQuery(".dropdown-stock").on('change', function(){
            $('.dropdown-qty').attr('data-select-available-qty',
                ($('.dropdown-stock :selected').attr("data-select-avai-qty")));
            $('.dropdown-qty').attr('data-option-id', $(this).val());
        });

        jQuery(".dropdown-qty").on('keyup', function(){
           
            var regex = new RegExp("^[0-9]+$");
            if (regex.test(this.value)) {
                var reqQty = parseInt(this.value);
                    if(reqQty < 0) {
                        $(this).val(0);
                }
           
            var avaiQty = $(this).attr('data-select-available-qty');
            if(reqQty > avaiQty){
                $("#select-stock-msg")
                .html("Requested Qty "+reqQty+" Is Not Available")
                .show().delay(15000).fadeOut();
                $(this).val(0);
                $(".dropdown-qty").blur();
            } else {
                    $("#select-stock-msg").html("");
                }
            } else {
                $(this).val(0);
                $(".dropdown-qty").blur();
            }  
        });
    });
</script>