<?php //phpcs:disable ?>
<?php $message = $block->getMessageData(); ?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>
<?php $documents_required_msg = $_helperB2b->getConfigValue(
    'hookahshisha/productpage/productpageb2b_documents_verification_required'
);?>

<?php /*We have Remove all the document releted msg as per suggested by arina [B2BHW-846]  */ ?>
<?php if ($_helperB2b->getIsFinanceVerified() != 1):?>
    <div class="pending-tooltip">
        <div class="tooltip-inner">
            <?= $block->escapeHtml(__($documents_required_msg)) ?>
        </div>
    </div>
<?php endif; ?>
