<?php
/** phpcs:disable */
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Totals\Tax
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var $_source \Magento\Sales\Model\Order\Invoice */
$_source    = $block->getSource();
$_order     = $block->getOrder();
$_fullInfo  = $block->getFullTaxInfo();
$summaryDetailsFirst = ' summary-details-first';
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
if (empty($taxHelper)) {
    $taxHelper = $this->helper(\Magento\Tax\Helper\Data::class);
}
/** @var \Magento\Framework\Math\Random $randomHelper */
$randomHelper = $block->getData('randomHelper');
?>
<?php if ($block->displayFullSummary() && $_fullInfo) { ?>
    <tr class="summary-total" onclick="expandDetails(this, '.summary-details')">
    <?php } elseif ($_order->getExciseTax() || $_order->getSalesTax() || $_order->getShippingTaxAmount() > 0) { ?>
    <tr class="summary-total" onclick="expandDetails(this, '.summary-details')">
    <?php } else { ?>
    <tr>
    <?php } ?>
    <td class="label">
        <div class="summary-collapse" tabindex="0">
            <?php if ($taxHelper->displayFullSummary()): ?>
                <?= $block->escapeHtml(__('Total Tax')) ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('Tax')) ?>
            <?php endif; ?>
        </div>
    </td>
    <td>
        <?= /* @noEscape */ $block->displayAmount($_source->getTaxAmount(), $_source->getBaseTaxAmount()) ?>
    </td>
    </tr>

    <?php $isTop = 1; ?>
    <?php if ($_source->getExciseTax()) { ?>
        <tr style="display: none;" id="info-123456" class="summary-details<?= ($isTop ? $summaryDetailsFirst : '') ?>">
            <td colspan="2" class="admin__total-mark" style="text-align: left;">Tobacco Tax : <?= /* @noEscape */ $block->displayAmount($_source->getExciseTax(), $_source->getExciseTax()) ?></td>
        </tr>
    <?php } ?>
    <?php if ($_source->getSalesTax()) { ?>
        <tr style="display: none;" id="info-12345678" class="summary-details<?= ($isTop ? $summaryDetailsFirst : '') ?>">
            <td colspan="2" class="admin__total-mark" style="text-align: left;">Sales Tax : <?= /* @noEscape */ $block->displayAmount($_source->getSalesTax(), $_source->getSalesTax()) ?></td>
        </tr>
    <?php } ?>
    <?php if ($_source->getShippingTaxAmount() > 0) { ?>
        <tr style="display: none;" id="info-1234567890" class="summary-details<?= ($isTop ? $summaryDetailsFirst : '') ?>">
            <td colspan="2" class="admin__total-mark" style="text-align: left;">Shipping Tax : <?= /* @noEscape */ $block->displayAmount($_source->getShippingTaxAmount(), $_source->getShippingTaxAmount()) ?></td>
        </tr>
    <?php } ?>


    <?php if ($block->displayFullSummary()): ?>
        <?php $isTop = 1; ?>
        <?php if (isset($_fullInfo[0]['rates'])): ?>
            <?php foreach ($_fullInfo as $info): ?>
                <?php if (isset($info['hidden']) && $info['hidden']):
                    continue;
                endif; ?>
                <?php
                $percent    = $info['percent'];
                $amount     = $info['amount'];
                $baseAmount = $info['base_amount'];
                $rates      = $info['rates'];
                $isFirst    = 1;
                ?>

                <?php foreach ($rates as $rate): ?>
                    <tr id="rate-<?= /* @noEscape */ $rate->getId() ?>" class="summary-details<?= ($isTop ? $summaryDetailsFirst : '') ?>" style="display:none;">
                        <?php if ($rate['percent'] !== null): ?>
                            <td class="admin__total-mark">
                                <?= $block->escapeHtml($rate['title']) ?> (<?= (float)$rate['percent'] ?>%)<br />
                            </td>
                        <?php else: ?>
                            <td class="admin__total-mark"><?= $block->escapeHtml($rate['title']) ?><br /></td>
                        <?php endif; ?>
                        <?php if ($isFirst): ?>
                            <td rowspan="<?= count($rates) ?>">
                                <?= /* @noEscape */ $block->displayAmount($amount, $baseAmount) ?>
                            </td>
                        <?php endif; ?>
                    </tr>

                    <?php
                    $isFirst = 0;
                    $isTop = 0;
                    ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php else: ?>
            <?php $cnt = 0; ?>
            <?php foreach ($_fullInfo as $info): ?>
                <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $isFirst    = 1;
                $cnt++;
                $infoId = $cnt;
                ?>
                <tr id="info-<?= /* @noEscape */ $infoId ?>" class="summary-details<?= ($isTop ? $summaryDetailsFirst : '') ?>" style="display:none;">
                    <?php if ($info['percent'] !== null): ?>
                        <td class="admin__total-mark">
                            <?= $block->escapeHtml($info['title']) ?> (<?= (float)$info['percent'] ?>%)<br />
                        </td>
                    <?php else: ?>
                        <td class="admin__total-mark"><?= $block->escapeHtml($info['title']) ?><br /></td>
                    <?php endif; ?>
                    <td><?= /* @noEscape */ $block->displayAmount($amount, $baseAmount) ?></td>
                </tr>
                
                <?php
                $isFirst = 0;
                $isTop = 0;
                ?>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php /** phpcs:enable */ ?>