<?php
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
use HookahShisha\Customization\Plugin\Magetrend\Order\Pdf\MagetrendInvoice;

$_item = $block->getItem();
$order = $block->getOrder();
$address = $order->getShippingAddress();
$helper =  $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
$kentuckyStateId = $helper->getConfigValue(MagetrendInvoice::KN_REGION_ID_CONFIG_PATH);
$canShowTaxColumn = $address->getRegionId() == $kentuckyStateId;
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <div class="tooltip content">
                                <dl class="item options">
                                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                    <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                </dl>
                            </div>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                    <dd><?= $block->escapeHtml($optionValue) ?></dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyCanceled() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                <span class="content"><?= (float) $block->getItem()->getQtyRefunded() ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <?php if ($canShowTaxColumn): ?>
        <td class="col tax" data-th="<?= $block->escapeHtml(__('Tax')) ?>">
            <?php
            /** @var \Magento\Framework\Pricing\Helper\Data $priceHelper */
            $priceHelper = $this->helper(Magento\Framework\Pricing\Helper\Data::class);
            ?>
            <?= $block->escapeHtml($priceHelper->currency($_item->getTaxAmount(), true, false)) ?>
        </td>
    <?php endif; ?>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
    <td class="col action" data-th="<?= $block->escapeHtml(__('Action')) ?>"
        data-product-id="<?= (float) $block->getItem()->getProductId() ?>">
        <?php
        $id = $block->getItem()->getProductId();
        $helper =  $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
        $isAvail = $helper->getStockStatus($id);
        if ($isAvail) { ?>
            <a href="javascript:void(0)" data-post='<?=
                /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                ->getPostData($this->helper(HookahShisha\Customerb2b\Helper\Data::class)
                ->getReorderUrl($block->getItem()->getItemId()))?>'>
                <?= $block->escapeHtml(__('Reorder Item')) ?></a>
                <?php } else { ?>
                    <?= $block->escapeHtml(__('Out Of Stock')) ?>
                <?php }  ?>
    </td>
</tr>
