<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php if ($block->isEditMode()): ?>
<form action="<?php echo $block->getProductEditUrl(); ?>" name="subscription_profile_update" id="subscription_profile_update" method="post" data-mage-init='{"validation":{}}'>
    <?php echo $block->getBlockHtml('formkey'); ?>
<?php endif; ?>
<div class="info-table">
    <ul class="content-left">
        <li class="product-img">
            <img class="prothumbimg" src="<?php echo $block->getProductImageUrl($block->getSubscription()->getProductId()); ?>" />
        </li>
    </ul>
    <ul class="content-right">
        <li class="subscription-datails">
            <span class="label"><?php echo __('Product Name:'); ?></span>
            <span class="value">
                <?php if ($block->getProductUrl() == '#'): ?>
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProductName()); ?>
                <?php else: ?>
                <a href="<?php echo $block->getProductUrl(); ?>" target="_blank">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProductName()); ?>
                </a>
                <?php endif; ?>

                <?php if ($productOptions = $block->getProductOption()) { ?>
                    <dl class="item-options">
                        <?php foreach ($productOptions as $optionKey => $option) { ?>
                            <dt><?= $option['label'] ?> :</dt>
                            <dd><?= $option['value'] ?></dd>
                        <?php } ?>
                    </dl>
                <?php } ?>
            </span>
        </li>
        <li class="product-sku">
            <span class="label"><?php echo __('SKU:'); ?></span>
            <span class="value"><?php echo $block->getSubscription()->getProductSku(); ?></span>
        </li>
        <li class="billing-price">
            <span class="label"><?php echo __('Billing Price:'); ?></span>
            <span class="value"><?php echo $block->getBillingAmount() ?></span>
        </li>
        <li class="quantity">
            <span class="label"><?php echo __('Quantity:'); ?></span>
            <span class="value">
                <?php if ($block->isEditMode()): ?>
                    <input type="text" name="qty" value="<?php echo $block->getQtyOrdered() ?>"
                    class="input-text required-entry validate-greater-than-zero validate-digits"
                    aria-required="true"/>
                <?php else: ?>
                    <?php echo $block->getQtyOrdered() ?>
                <?php endif; ?>
            </span>
        </li>
        <li class="trial-price">
            <?php if ($block->getSubscription()->getTrialBillingAmount() > 0): ?>
                <span class="label"><?php echo __('Trial Price:'); ?></span>
                <span class="value"><?php echo $block->getTrialAmount() ?></span>
            <?php endif; ?>
        </li>
        <li class="initial-price">
            <?php if ($block->getSubscription()->getInitialAmount() > 0): ?>
                <span class="label"><?php echo __('Initial Price:'); ?></span>
                <span class="value"><?php echo $block->getInitialAmount() ?></span>
            <?php endif; ?>
        </li>
    </ul>
</div>
<div class="subscription-disclaimer">
    <span><sup><?= __('** All prices are displayed as per unit price') ?></sup></span>
</div>
<?php if ($block->isEditMode()): ?>
<div class="back-subscription">
    <button type="button"  onclick="updatSubscriptionForm()" title="<?php echo __('Apply Changes') ?>" class="button button action tocart primary" id="subscription_update">
        <span><span><?php echo __('Apply Changes') ?></span></span>
    </button>
    <button type="button" onclick="location.href=removeEditForm();" title="<?php echo __('Cancel') ?>" class="button button action tocart primary" id="subscription_cancel">
        <span><span><?php echo __('Cancel') ?></span></span>
    </button>
</div>
</form>
<script type="text/javascript">
    function updatSubscriptionForm()
    {
        var dataForm = jQuery('#subscription_profile_update');
        dataForm.mage('validation');
        if (jQuery('#subscription_profile_update').valid()) {
            jQuery('#subscription_update').attr('disabled', true);
            jQuery('#subscription_profile_update').submit();
        }
    }
    function removeEditForm() {
        var url = window.location.href.replace('/edit/1/', '/');
        return url;
    }
</script>
<?php endif; ?>