<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $shippingMethod=$block->getOrder()->getShippingMethod();
$viewModel = $block->getData('view_model');
$websiteId = $block->getOrder()->getStore()->getWebsiteId();
$grossEnable = $viewModel->isModuleEnabled('hookahshisha/gross_margin_group/gross_margin_enable', $websiteId);?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    unset($columns['carriergroup']);
    unset($columns['carriergroup_shipping']);
    if ($grossEnable === '0') {
        unset($columns['grossmargin']);
    }
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass): ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
            <?= $block->getColumnHtml($_item, $columnName) ?>
        </td>
    <?php endforeach; ?>
</tr>