<?php //phpcs:disable ?>
<?php
    /**
     * Grouped product data template
     *
     * @var $block \Magento\Catalog\Block\Product\View\BaseImage
     * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
     */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>
<?php $is_document_upload = $_helperB2b->getDocuments();?>
<?php $is_mobile = $_helperB2b->isMobileDevice();?>
<?php $adminsession = $_helperB2b->getAdminCustomer();?>
<?php $IsFinanceVerified = $_helperB2b->getIsFinanceVerified();?>

    <div id="validation-message-box"></div>
    <div class="table-wrapper grouped">
        <table class="table data grouped"
        id="super-product-table"
        data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <?php if ($_hasAssociatedProducts): ?>
             <?php $sortedProducts = $block->getSortedProducts();
            ?>
            <tbody>
                <?php foreach ($sortedProducts as $_item): ?>
                    <?php $productAvailableQty = $_helperB2b->getStockQty($_item->getId()); ?>
                    <tr>
                    <?php
                    $cost = $_helperB2b->getGrossMargin($_item->getId());
                    $grossMargin = ($_item->getPrice() - $cost) / $_item->getPrice() * 100;
                     $finalGrossMargin = number_format($grossMargin, 2, ".", "");
                    ?>
                      <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <?php if ($adminsession): ?>
                            <strong class="product-item-name" title="<?= $block
                            ->escapeHtml('Qty : '.$productAvailableQty.' , GrossMargin : ' . $finalGrossMargin.'%') ?>">
                            <?= $block->escapeHtml($_item->getName()) ?>
                            </strong>
                        <?php else: ?>
                            <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                        <?php endif; ?>
                        </td>
                        <?php
                        /*
                        Here we removed the condition of the Document verified
                        ( $is_document_upload $doc_expired) and uploaded($IsFinanceVerified)
                        */
                        ?>
                        <?php
                        $messageData=$_helperB2b->getDocMessageData();
                        $expiryMsg=$_helperB2b->getExpiryMsg();

                        if ($IsFinanceVerified == 1): ?>
                            <td>
                               <?php if ($block->getCanShowProductPrice($_product)): ?>
                                    <?php if ($block->getCanShowProductPrice($_item)): ?>
                                        <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php /* bv_op; date : 10-2-22; Start */ ?>
                            <div class="bv-special-price-<?= $block->escapeHtmlAttr($_item->getId()) ?>"></div>
                            <?php /* bv_op; date : 10-2-22; End */ ?>

                        </td>
                            <?php if ($_helperB2b->isCustomerLoggedIn()): ?>
                                <?php if ($_product->isSaleable()): ?>
                                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                                    <?php if ($_item->isSaleable()): ?>
                                        <div class="control qty">
                                            <?php
                                            
                                            if ($is_mobile):
                                                //Write your code here for Mobile view
                                                $qtyCounter=$block->getProductDefaultQty() * 1 ;
                                                $dataValidate=json_encode($block->getQuantityValidators());
                                                ?>
                                                <select class="input-text qty" 
                                                name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]" 
                                                data-selector="super_group[
                                                <?= /* @noEscape */ $block->escapeHtmlAttr($_item->getId()) ?>]"
                                                id="qtydrop_<?= $block->escapeHtmlAttr($_item->getId()) ?>" 
                                                data-validate="{'validate-custom-grouped-qty':'#super-product-table'}"
                                                data-errors-message-box="#validation-message-box"
                                                data-product-id
                                                ="<?= /* @noEscape */ $block->escapeHtmlAttr($_item->getId()) ?>"
                                                data-product-available-qty
                                                ="<?= $block->escapeHtmlAttr($productAvailableQty) ?>"
                                                >
                                                <?php $qtyCounter = $block->escapeHtmlAttr($_item->getQty() * 1);
                                                for ($qtyCounter; $qtyCounter<=100; $qtyCounter++):
                                                    $selected='';
                                                    if ($block->escapeHtmlAttr($_item->getQty() * 1) == $qtyCounter):
                                                        $selected='selected';
                                                    endif; ?>
                                                    <option value="<?= /* @noEscape */ $qtyCounter; ?>" 
                                                        <?= /* @noEscape */  $selected; ?>>
                                                        <?= /* @noEscape */  $qtyCounter; ?></option>
                                                    <?php endfor; ?>
                                                </select>
                                            <?php else: ?>
                                               <input type="text"
                                               name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                                               data-selector="super_group[<?= $block->
                                                escapeHtmlAttr($_item->getId()) ?>]"
                                               value="<?=  $block->escapeHtmlAttr($_item->getQty() * 1) ?>"
                                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                               id="qtytext_<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                               class="input-text qty err-show"
                                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                               data-errors-message-box="#validation-message-box"
                                               data-product-id="<?=  $block->escapeHtmlAttr($_item->getId()) ?>"
                                               data-product-available-qty
                                               ="<?= $block->escapeHtmlAttr($productAvailableQty) ?>"
                                               onclick="this.select();"/>
                                           <?php endif; ?>
                                                <span id="qtymessage_<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                                    style="color: red;"></span>
                                       </div> 
                                   <?php else: ?>
                                    <div class="stock unavailable" 
                                    title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                <?php endif; ?>
            </tr>
                    <?php if ($block->getCanShowProductPrice($_product)
                    && $block->getCanShowProductPrice($_item)
                    && trim($block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                    ))): ?>
                <tr class="row-tier-price" style="display: none;">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </tbody>
    <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                colspan="<?php if ($_product->isSaleable()): ?>4<?php else: ?>3<?php endif; ?>">
                <?= $block->escapeHtml(__('No options of this product are available.')) ?>
            </td>
        </tr>
    </tbody>
    <?php endif; ?>
    </table>
    </div>

    <script type="text/x-magento-init">
       {
           "*": {
               "validateCustomGroupedQty": {}
           }
       }
    </script>
    <?php /* bv_op; date : 10-2-22; Start */ ?>
    <script>
        require(['jquery'], function ($) {

            $(".col.qty .control.qty .input-text.qty").on("change paste keyup", function (e) {
                if (typeof $(this).val() !== 'undefined' && $(this).val() != '' && $(this).val() > 0) {
                    var requestQty = parseInt($(this).val());
                    var productId = $(this).data('product-id');
                    var exist = $("[name='"+productId+"-qty[]']").length;
                    if(exist && typeof exist !== 'undefined'){
                        var bvSpecialPrice = 0;
                        $.each($("[name='"+productId+"-qty[]']"), function (index, value) {
                            var bvSpecialPriceQty = parseInt($(value).val());
                            if (requestQty >= bvSpecialPriceQty) {
                                bvSpecialPrice = $("[name='"+productId+"-qty-"+$(value).val()+"']").val();
                            }
                        });

                        if (bvSpecialPrice != 0) {
                            var priceHtml="<span><strong>$"+parseFloat(bvSpecialPrice).toFixed(2)+"</strong></span>";
                            $(".bv-special-price-"+productId).html(priceHtml);
                            $(this).parents('td').prev('td').find("span.price").addClass('old-price');
                        }else{
                            $(".bv-special-price-"+productId).html("");
                            $(this).parents('td').prev('td').find("span.price").removeClass('old-price');
                        }
                    }

                }else{
                    var productId = $(this).data('product-id');
                    $(".bv-special-price-"+productId).html("");
                    $(this).parents('td').prev('td').find("span.price").removeClass('old-price');
                }

            });
            /*bv-hd for desktop checkqty*/
            $("[id^='qtytext_']").on("keydown keyup",function(e){
                var currentId= $(this).attr('id');
                var regex = new RegExp("^[0-9]+$");
                if (regex.test(this.value)) {
                    var requestQty = this.value;
                    if(requestQty < 0){
                        $(this).val(0);
                    }
                    var productId= $(this).data('product-id');
                    var availableProductQty = $(this).data('product-available-qty');
                    if(requestQty > availableProductQty){
                        $("#qtymessage_"+productId)
                        .html("Requested Qty "+requestQty+" Is Not Available")
                        .show().delay(15000).fadeOut();
                        $(this).val(0);
                        $("#"+currentId).blur();

                    }else{
                        $(this).val(parseInt(requestQty));
                        $("#qtymessage_"+productId).html("");
                    }
                }else{
                     $(this).val(0);
                     $("#"+currentId).blur();
                }
            });
            /*bv-hd for mobile checkqty*/
            $("[id^='qtydrop_']").on('change',function(){
                var requestQty = this.value;
                var productId= $(this).data('product-id');
                var availableProductQty = $(this).data('product-available-qty');
                if(requestQty > availableProductQty){
                    $(this).val(0);
                    $("#qtymessage_"+productId)
                    .html("Requested Qty "+requestQty+" Is Not Available")
                    .show().delay(15000).fadeOut();
                }else{
                    $("#qtymessage_"+productId).html("");
                }
            });
        });
    </script>
    <?php /* bv_op; date : 10-2-22; End */ ?>

<script>
    require(['jquery'], function ($) {

     function setSelectionRange(input, selectionStart, selectionEnd) {
      if (input.setSelectionRange) {
        input.focus();
        input.setSelectionRange(selectionStart, selectionEnd);
      }
    }

    function setCaretToPos(input, pos) {
        setSelectionRange(input, pos, pos);
    }

    $(document).ready(function() {
        $(document).on("click", '#product-addtocart-button', function(e){
            if(!$(".err-show").valid()){
                setCaretToPos($(".err-show")[0], 1);
            }
            else{
                $(".err-show").blur();
            }
        });
    });
});
</script>
