<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->hasAdditionalInfo()) : ?>
    <div class="product-options-wrapper subscription-field">
        <?php foreach ($block->getAdditionalInfo() as $label => $value) :?>
            <div class="product-admin-options field">
                <label class="label"><?= /* @escapeNotVerified */ $label ?> </label>
                <div class="control"><span><?= /* @escapeNotVerified */ $value ?></span></div>
            </div>
        <?php endforeach; ?>
        </div>
<?php endif; ?>
