<?php
/** @var \ParadoxLabs\TokenBase\Block\Customer\Cards $block */
?>
<div class="block block-cards-list">
    <?php $cards = $block->getCards(); ?>
    <?php if (count($cards)>0): ?>
    <div class="block-title">
        <h2><?= $block->escapeHtml($block->getPaymentMethodTitle()); ?></h2>
    </div>
    <?php endif;?>
    <div class="block-content items checkout-payment-method">
        <?php if (!empty($cards)): ?>
            <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
            <?php foreach ($cards as $card): ?>
                <?php $card = $card->getTypeInstance(); ?>
                <?php $expiredClass = ""; ?>
                <?php if ($card->getExpires() != '' && strtotime($card->getExpires()) < time()): ?> 
                    <?php $expiredClass = "expired"; ?>
                <?php endif; ?>
                <fieldset class="box-address-billing 
                    payment-method-title 
                    fieldset <?= $block->escapeHtml($expiredClass) ?>">
                    <div class="box-title legend">
                        <?php if (!empty($card->getType())): ?>
                            <?php $cardType = strtolower($card->getType()); ?>
                            <?php $cardUrl=$block->getViewFileUrl('Magento_Payment::images/cc/'.$cardType.'.png'); ?>
                            <img class="credit-card-type payment-icon" 
                                src="<?= $block->escapeUrl($cardUrl) ?>" 
                                alt="<?= $block->escapeHtmlAttr($block->getCcTypeLabel($card)); ?>" />
                        <?php endif; ?>
                        <strong class="payment-icon">
                            <span>
                                <?= $block->escapeHtml($card->getLabel(empty($card->getType()))); ?>
                            </span>
                        </strong>
                        <?php if (strtotime($card->getExpires()) > time()): ?>
                            <small>
                                <?php $expireDate = date('m/Y', strtotime($card->getExpires())); ?>
                                <?= $block->escapeHtml(__('(Expires %1)', $expireDate)); ?>
                            </small>
                        <?php endif; ?>
                    </div>
                    <div class="box-content">
                        <address>
                            <?= /* @noEscape */ $block->getFormattedCardAddress($card->getAddressObject()); ?>
                        </address>
                        <div class="item actions box-actions">
                            <?php if ($card->isInUse()): ?>
                                <?php $cardTitle="This payment record cannot be modified "; ?>
                                <?php $cardTitle.="while associated with pending orders."; ?>
                                <abbr 
                                    title="<?= $block->escapeHtmlAttr(__($cardTitle)); ?>">
                                    <?= $block->escapeHtml(__('Card In Use')); ?>
                                </abbr>
                            <?php else: ?>
                                <a class="action edit" 
                                    href="<?= $block->escapeUrl($block->getUrl(
                                        '*/*',
                                        [
                                                '_secure' => true,
                                                'form_key' => $block->getFormKey(),
                                                'method' => $card->getMethod(),
                                                'id' => $card->getHash()
                                            ]
                                    )) ?>">
                                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                                </a>
                                <a class="action delete" 
                                    href="<?= $block->escapeUrl($block->getUrl(
                                        '*/*/delete',
                                        [
                                                '_secure' => true,
                                                'form_key' => $block->getFormKey(),
                                                'method' => $card->getMethod(),
                                                'id' => $card->getHash()
                                            ]
                                    )) ?>">
                                    <span><?= $block->escapeHtml(__('Delete')) ?></span>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </fieldset>
            <?php endforeach; ?>
        <?php else: ?>
            <p><?= $block->escapeHtml(__('You do not have any payment data saved yet.')) ?></p>
        <?php endif; ?>
    </div>
</div>
