<?php
/**
 * Magedelight
 * Copyright (C) 2022 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php
$profileid='';$status='';$fromdate = '';$todate='';
if($this->getRequest()->get('profileid') !== "null") {
    $profileid = $this->getRequest()->get('profileid');
}
if($this->getRequest()->get('status') !== "null") {
    $status = $this->getRequest()->get('status');
} 
if($this->getRequest()->get('fromdate') !== "null") {
    $fromdate = $this->getRequest()->get('fromdate');
} 
if($this->getRequest()->get('todate') !== "null") {
    $todate = $this->getRequest()->get('todate');
}  
?>
<div class="profile-filter">
        <label><strong><?php /* @escapeNotVerified */ echo __('Filter') ?></strong></label>
        <form method="GET" action="<?= $block->getCurrentUrl(); ?>" id="profilefilter" role="form" name="profilefilter">
            <div class="profile-content">
                <div class="profileid">
                    <label>Profile Id:</label>
                    <div class="control">
                        <input type="text" name="profileid" value="<?php echo $profileid; ?>" class="profileid"/>
                    </div>
                </div>
                <div class="nextorderdate">
                    <label>Next Order Date:</label>
                    <div class="control">
                        <input type="text" placeholder="From" name="fromdate" value="<?php echo $fromdate; ?>" class="datepicker"/>
                        <input type="text" placeholder="To" name="todate" value="<?php echo $todate; ?>" class="datepicker"/>
                    </div>
                </div>
                <div class="status">
                    <label>Status:</label>
                    <select name="status" id="status">
                    <option value=""><?php /* @escapeNotVerified */ echo __('--- Please select Status ---') ?></option>
                        <?php foreach($block->getProfileStatus() as $key=>$value) : ?>
                            <option value="<?php echo $key; ?>" <?php if($key == $status) { echo "selected"; } ?>><?php echo $value; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" title="Submit" id="profile-btn" class="action submit primary">
                            <span>Submit</span>
                        </button>
                        <button type="button" title="Clear" class="clear-button" id="profile_clear"><span>Clear</span></button>
                    </div>
                </div>
            </div>
        </form>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'mage/calendar'
    ], function ($, script) {
        $(document).ready(function() {
            var status = "<?php echo $status; ?>"
            if(status == '') {
            $("#status > [value='']").attr("selected", "true");
            }
        });
        $(".datepicker").datepicker({
            showMonthAfterYear: false,
            dateFormat: 'yy-mm-dd',
            changeMonth: true,
            changeYear: true,
            yearRange: '+0:+10',
            minDate: new Date(),
        });
        $('#profile_clear').click(function(){
            var uri = window.location.href.toString();
            if (uri.indexOf("?") > 0) {
                var clean_uri = uri.substring(0, uri.indexOf("?"));
                window.history.replaceState({}, document.title, clean_uri);
            }
            window.location.reload();
        });
    });
</script>