<?php
/**
 * @var $block \Magento\OfflinePayments\Block\Form\OfflinePaypal
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>">
    <div class="admin__field _required">
        <label for="paypal_email" class="admin__field-label">
            <span><?= $block->escapeHtml(__('PayPal Email')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="email" id="paypal_email" name="payment[paypal_email]"
                   title="<?= $block->escapeHtml(__("Purchase Order Number")) ?>"
                   class="required-entry admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('paypal_email') ?>"/>
        </div>
    </div>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display:none",
    'fieldset#payment_form_' . $block->escapeJs($block->getMethodCode())
) ?>