<?php

use Magento\Framework\View\Helper\SecureHtmlRenderer;

?>
<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Items\Column\Name
 * @var SecureHtmlRenderer $secureRenderer
 */

?>
<?php
$catalogHelper = $block->getData('catalogHelper');

/** @var Ooka\OokaSerialNumber\ViewModel\SerialCode $viewModel */
$viewModel = $block->getData("serial_code");

?>
<?php
if ($_item = $block->getItem()): ?>

    <div id="order_item_<?= (int)$_item->getId() ?>_title"
         class="product-title">
        <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU')) ?>:</span>
        <?= /* @noEscape */
        implode('<br />', $catalogHelper->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>
    <div>
        <?php
        $serialcode = $viewModel->
        getSerialNumbers($_item->getSku(), $_item->getOrder()->getIncrementId(), $_item->getItemId());
        if (!empty($serialcode) && !empty($_item->getData('is_serialize'))) {
            ?>
        <span STYLE="font-weight:bold"><?= $block->escapeHtml(__('Serial No:')) ?></span><br>
        <span STYLE="font-weight:bold">
                    <?php
                    $qty = 0;
                    foreach ($serialcode as $key => $code) {
                        if ($qty < $_item->getQtyOrdered()) {
                            /* @noEscape */
                            echo $code;
                            if (isset($serialcode[$key + 1])) {
                                echo ',';
                                echo '</br>';
                            }
                        }
                        $qty++;
                    }

                    ?>
                    <?php
        }
        ?>
        </span>
    </div>
    <?php
    if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php
            foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
                <dd>
                    <?php
                    if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?= /* @noEscape */
                        $block->getCustomizedOptionValue($_option) ?>
                        <?php
                    else: ?>
                        <?php
                        $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php
                        $dots = 'dots' . uniqid(); ?>
                        <?php
                        $id = 'id' . uniqid(); ?>
                        <?= $block->escapeHtml($_option['value'], ['a', 'br']) ?>
                        <?php
                        if (isset($_option['remainder']) && $_option['remainder']): ?>
                            <span id="<?= /* @noEscape */
                            $dots; ?>"> ...</span>
                            <span id="<?= /* @noEscape */
                            $id; ?>">
                                <?= $block->escapeHtml($_option['remainder'], ['a']) ?>
                            </span>
                            <?php
                            $scriptString = <<<script
                                require(['prototype'], function() {

script;
                            $scriptString .= "$('" . /* @noEscape */
                                $id . "').hide();" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */
                                $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */
                                $id . "').show();});" .
                                PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */
                                $id .
                                "').up().observe('mouseover', function(){ $('" . /* @noEscape */
                                $dots .
                                "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */
                                $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */
                                $id .
                                "').hide();});" . PHP_EOL;
                            $scriptString .= "$('" . /* @noEscape */
                                $id .
                                "').up().observe('mouseout',  function(){ $('" . /* @noEscape */
                                $dots .
                                "').show();});" . PHP_EOL . "});" . PHP_EOL;
                            ?>
                            <?= /* @noEscape */
                            $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                            <?php
                        endif; ?>
                        <?php
                    endif; ?>
                </dd>
                <?php
            endforeach; ?>
        </dl>
        <?php
    endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
    <?php
endif; ?>
