<?php

declare(strict_types=1);

namespace HookahShisha\SubscribeGraphQl\Model\ResourceModel;

use Magento\Framework\DataObject;

class ProductSubscribers extends \Magedelight\Subscribenow\Model\ResourceModel\ProductSubscribers
{
    protected function _serializeField(DataObject $object, $field, $defaultValue = null, $unsetEmpty = false)
    {
        // Fix to prevent multiple serialization
        if (!is_array($object->getData($field))) {
            return $this;
        }
        return parent::_serializeField($object, $field, $defaultValue, $unsetEmpty); // TODO: Change the autogenerated stub
    }
}
