<?php
/**
 * Magedelight
 * Copyright (C) 2018 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2018 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>

<?php
/**
 *
 * @var $block \Magedelight\Subscribenow\Block\Catalog\Product\View\Subscription\BillingDate
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div id="md_subscription_content_start" class="product-options-wrapper subscription-field subscription-start">
    <div class="field">
        <label for="md_subscription_start" class="label">
            <?= __('Subscription Start Date:'); ?>
        </label>
        <?php if ($block->isCustomerDefined()): ?>
        <div class="control">
            <input type="text" id="md_subscription_start" readonly="readonly"
                   name="subscription_start_date" class="input-text" value="<?= $block->getCurrentDate(); ?>"/>
        </div><em class="note small"></em>
    <?php else: ?>
        <div class="control">
            <span><?= $block->getSubscriptionDate(); ?></span>
            <input type="hidden" name="subscription_start_date" value="<?= $block->getSubscriptionDate() ?>" />
        </div>
    <?php endif; ?>
    </div>
</div>
<div class="product-options-wrapper subscription-field subscription-end">
    <div class="field">
        <label for="md_subscription_end" class="label">
            <?= __('Subscription End By:'); ?>
        </label>
        <div class="md_end_type last">
            <input type="radio" id="end_by_cycle" name="end_type" value="md_end_cycle" class="radio required-entry"
                   data-validate="{'validate-one-required-by-name':true}"
                <?= $block->isCheckedType("md_end_cycle"); ?>>
            <label for="end_by_cycle" class="label">
                <div class="dot"></div>
                <?= __('End By Cycle'); ?>
                <span class="field-tooltip-action">
                    <a href="#" class="tooltip-toggle">hover me</a>
                    <span class="tooltip-content">
                        <?= __('This will create a subscription order until mentioned delivery cycle completed. 
                        I.e. 3 Cycle means 3 orders to be delivered.'); ?></span>
                </span>
            </label>
            <div class="end_type_content" style="display: none;">
                <div class="control required">
                    <input type="text" id="md_subscription_cycle" name="subscription_end_cycle"
                           value="<?= $block->getSubscriptionEndCycle(); ?>"
                           class="input-text required-entry validate-greater-than-zero validate-digits"/>
                    <span><?= __('orders'); ?></span>
                </div>
            </div>
        </div>
        <?php if($block->isAllowedSubscriptionEndDate()): ?>
        <div class="md_end_type">
            <input type="radio" id="end_by_date" name="end_type" value="md_end_date" class="radio required-entry"
                   data-validate="{'validate-one-required-by-name':true}"
                <?= $block->isCheckedType("md_end_date"); ?>>
            <label for="end_by_date" class="label">
                <div class="dot"></div>
                <?= __('End By Date'); ?>
                <span class="field-tooltip-action">
                    <a href="#" class="tooltip-toggle">hover me</a>
                    <span class="tooltip-content">
                        <?= __('This will create a subscription order until mentioned end date completed. 
                        I.e. If your start date is 1st Jan end date is 30th Jan and frequency is daily 
                        that means 30 orders to be delivered.'); ?></span>
                </span>
            </label>
            <div class="end_type_content" style="display: none;">
                <div class="control">
                    <input type="text" id="md_subscription_end" readonly="readonly" name="subscription_end_date"
                           class="input-text" value="<?= $block->getSubscriptionEndDateSelected(); ?>"/>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="md_end_type">
            <input type="radio" id="infinite" name="end_type" value="md_end_infinite" class="radio required-entry"
                   data-validate="{'validate-one-required-by-name':true}" <?= $block->isCheckedType("md_end_infinite"); ?>>
            <label for="infinite" class="label">
                <div class="dot"></div>
                <?= __('Until you cancel'); ?>
                <span class="field-tooltip-action">
                    <a href="#" class="tooltip-toggle">hover me</a>
                    <span class="tooltip-content">
                        <?= __('This will create subscription order until you cancel it from your My Account 
                        or your payment get failed multiple times.'); ?></span>
                </span>
            </label>
            <div class="end_type_content">
                &nbsp;
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(["jquery", "MagedelightSubscription"],
        function ($, subscription) {
            subscription.initDatePicker({
                allowStartDate: "<?= $escaper->escapeJs($block->isCustomerDefined()); ?>",
                allowEndDate: "<?= $block->isEndDateAllowed() ?>",
                startDate: "<?= $block->getSubscriptionSelectedDate(); ?>",
                endDate: new Date('<?= $block->getSubscriptionEndDateSelected(); ?>'),
                minDate: new Date('<?= $block->getCurrentDate(); ?>'),
                initialFee: "<?= $block->getInitialAmount(false); ?>",
            });
        }
    );
</script>
