<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php if ($block->isBundle() || $block->isConfigurable() || $block->isGrouped()): ?>
<input
    type="hidden"
    value="<?= $block->escapeHtml($block->getDiscountConfig()) ?>"
    id="md_subscription_discount_config"
    disabled=""
    class="hidden disable" />
<?php endif; ?>

<?php if ($block->canPurchaseSeparately()): ?>
    <div class="subscribe-control-option">
        <div class="purchase-option-left">
            <input type="radio" value="nosubscription" id="no_subscription" class="radio admin__control-radio required product-custom-option" name="options[_1]"<?php echo (!$block-> isSubscriptionChecked())?"checked=checked":""?> >
                <label for="no_subscription">
                    <div class="dot"></div>
                    <?= $block->escapeHtml($block->getFirstSubscriptionLabel()); ?>
                </label>
        </div>
        <div class="purchase-option-right">
            <input type="radio" value="subscription" id="subscribe_this_product" class="radio admin__control-radio required product-custom-option" name="options[_1]" <?php echo ($block->isSubscriptionChecked())?"checked=checked":""?> >
                <label for="subscribe_this_product">
                    <div class="dot"></div>
                    <?= $block->escapeHtml($block->getSecondSubscriptionLabel()); ?>
                    <?php //echo $block->getSubscriptionLabel(); ?>
                </label>
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceOptions": {
                "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>,
                "controlContainer": ".field",
                "priceHolderSelector": "[data-role=priceBox]"
            }
        }
    }
</script>
<?php else: ?>
    <input type="hidden" value="subscription" name="options[_1]">
<?php endif; ?>
