<?= $block->getButtonHtml() ?>

<script type="text/javascript">
    require(['jquery','Magento_Ui/js/modal/alert'], function($){
        $(document).on('click','#generate_mega_menu', function (){
            var url      = window.location.href;
            $.ajax({
                url : "<?= /* @noEscape */ $block->getAjaxUrl() ?>",
                type : 'POST',
                showLoader : true,
                success : function (data){
                    alert(data.message);
                    window.location.href = url;
                }
            });
        });
    });
</script>