<?php
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-carousel';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
    $showCart = $_helperB2b->isCustomerLoggedIn();
    $IsFinanceVerified=$_helperB2b->getIsFinanceVerified();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <ol class="product-items <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item): ?>
            <?= /* @noEscape */ ($iterator++ == 1) ?
            '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                    <?= $block->getImage($_item, $image)->toHtml() ?>
                </a>
                <div class="product-item-details">
                    <p class="product-item-brand"><?= $block->escapeHtml($_item->getAttributeText('brand')) ?></p>
                    <strong class="product-item-name">
                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="product-item-link">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>
                    <?php if ($templateType): ?>
                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <?php endif; ?>
                    <?php if ($IsFinanceVerified == 1): ?>
                        <?= $block->getProductPriceHtml($_item, $type) ?>
                        <?= $block->getProductDetailsHtml($_item) ?>
                    <?php endif; ?>
                        <div class="product-item-inner">
                                <!-- check the document is uploaded or verified  -->                          
                                <?php if ($showCart): ?>
                                    <div class="actions-primary">
                                        
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                            <form
                                            data-role="tocart-form"
                                            data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>"
                                                action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                method="post">
                                                <input type="hidden"
                                                name="product"
                                                value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                <input type="hidden"
                                                name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"value="
                                                <?= /* @noEscape */ $postParams
                                                ['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <?php if ($IsFinanceVerified == 1): ?>
                                                <?php else: ?>
                                                    <div class="logged-in-action">
                                                        <a
                                                        href="<?= $block
                                                        ->escapeUrl($block
                                                        ->getProductUrl($_item)) ?>">
                                                        <?= $block->escapeHtml(__('View Details')) ?>
                                                        </a>
                                                    </div>
                                            <?php endif; ?>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available">
                                                    <span>
                                                        <?= $block->escapeHtml(__('In stock')) ?>
                                                    </span>
                                                </div>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span>
                                                        <?= $block->escapeHtml(__('Out of stock')) ?>
                                                    </span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php elseif (!$showCart): ?>
                                    <div class="logged-in-action">
                                        <a href="<?= $block->escapeUrl($block
                                        ->getUrl('customer/account/login')) ?>"
                                        >
                                        <?= $block->escapeHtml(__('Signin / Register')) ?>
                                        </a>
                                    </div>
                                <?php endif; ?>
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)
                                        ->isAllow() && $showWishlist): ?>
                                            <a href="#"
                                               data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                class="action towishlist"
                                               data-action="add-to-wishlist"
                                               title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                <span>
                                                    <?= $block->escapeHtml(__('Add to Wish List')) ?>
                                                </span>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this
                                            ->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                            <a href="#"
                                            class="action tocompare"
                                            data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                            title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                        </div>
                </div>
            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
        <?php endforeach ?>
    </ol>
<?php endif;?>
<script>
    require([
        "jquery"
    ], function ($) {
        $(document).ready(function() {
            let $progressBar = $('.progress');
            let $slider = $('.top_sellling > .widget-product-carousel');
            let $progressBarLabel = $( '.slider__label' );

            $slider.on('init', function(event, slick) {
                checkSlider(slick);
            });

            function checkSlider(slick) {
                let displayValue = $('.top_sellling > .widget-product-carousel > button').length ? 'block' : 'none';
    
                $progressBar.css('display', displayValue);
            }
            
            $slider.on('beforeChange', function(event, slick, currentSlide, nextSlide) {               
                let calc = ( (nextSlide) / (slick.slideCount-1) ) * 100;
                
                $progressBar
                .css('background-size', calc + '% 100%')
                .attr('aria-valuenow', calc );
                
                $progressBarLabel.text( calc + '% completed' );
            });
        });
    });
</script>