<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php
$blockObj = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
$_productCollection = $blockObj->getLoadedProductCollection();
?>
<div class="viewingproducts">
    Viewing <span id="productCount"><?php echo $_productCollection->count(); ?></span>
     of <span id="totalProductCount"><?php echo $_productCollection->getSize(); ?></span>
</div>

<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1) :?>
        <?= $block->escapeHtml(
            __(
                'Items %1-%2 of %3',
                '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
            ),
            ['span']
            ) ?>
    <?php elseif ($block->getTotalNum() == 1) :?>
        <?= $block->escapeHtml(
            __('%1 Item', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
            ) ?>
    <?php else :?>
        <?= $block->escapeHtml(
            __('%1 Items', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
            ) ?>
    <?php endif; ?>
</p>
