<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent">
    <h3 class="h2_heading_builder with_border_bottom"><?= $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="post-list post-list-slick clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $block->escapeUrl($_post->getPostUrl());
                $_postName = $block->escapeHtml($_post->getTitle());
            ?>
            <li class="post-holder post-holder-<?= (int)$_post->getId() ?>">
            <div class="post-holder-hover">
                <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                    <?php if ($featuredImage) { ?>
                        <?php
                            $featuredImgAlt = $_post->getData('featured_list_img_alt') ?:
                            $_post->getData('featured_img_alt');
                        if (!$featuredImgAlt) {
                            $featuredImgAlt = $_postName;
                        }
                        ?>
                        <div class="post-ftimg-hld">
                            <a href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                <img
                                src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-3.gif')) ?>"
                                image-data-src="<?= $block->escapeHtml($featuredImage) ?>"
                                alt="<?= $block->escapeHtml($featuredImgAlt) ?>" 
                                width="407" height="270" loading="lazy" /> 
                            </a>
                        </div>
                <?php } ?>

                <div class="post-content">

                    <div class="post-info clear">
                        <?php if ($_post->isPublishDateEnabled()) { ?>
                            <div class="item post-posed-date">
                                <span class="posted-icon">
                                    <img 
                                    src="<?= $block->escapeUrl($block->getViewFileUrl('images/calender-icon.svg')); ?>"
                                    alt="Calender" />
                                </span>
                                <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                            </div>
                        <?php } ?>
                         <!-- get Author name start -->
                         <?php if ($block->authorEnabled()) { ?>
                                <?php if ($_author = $_post->getAuthor()) { ?>
                                <div class="item post-author">
                                        <span class="label"><?= $block->escapeHtml(__('By:')) ?></span>
                                        <span class="value">
                                        <?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
                                        <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                           href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>">
                                        <?php } ?>

                                        <?= $block->escapeHtml($_author->getTitle()) ?>

                                        <?php if ($authorPageEnabled) { ?>
                                        </a>
                                        <?php } ?>
                                    </span>
                                </div>
                                <?php } ?>
                            <?php } ?>
                        <!-- End Author name -->                        
                    </div>

                    <div class="post-title-holder clearfix">
                        <div class="post-title">
                            <a class="post-item-link"
                               href="<?= /*@noEscape*/ $_postUrl ?>">
                                <?= /*@noEscape*/ $_postName ?>
                            </a>
                        </div>
                    </div>

                    <div class="post-description clearfix">                       
                        <div class="post-text-hld clearfix">
                            <?= /*@noEscape*/ $block->getShorContent($_post) ?>
                        </div>
                        <a class="post-read-more"
                           href="<?= /*@noEscape*/ $_postUrl ?>"
                           title="<?= /*@noEscape*/ $_postName ?>"
                           >
                           <?= $block->escapeHtml(__('Read more')) ?>
                           <span class="svg_icon">
                            <svg width="10" height="14" viewBox="0 0 6 10" fill="none" 
                            xmlns="http://www.w3.org/2000/svg">
                                <path d="M1 1L5 5L1 9" stroke="#838282" stroke-width="1" 
                                    stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                           </span>
                        </a>
                    </div>
                </div>
            </div>
            </li>

        <?php } ?>
    </ul>
    <div class="view-more primary">
        <a href="<?= $block->escapeUrl($block->getBaseUrl().'blog'); ?>" 
            class="action primary"><?= $block->escapeHtml(__('View More')) ?>
        </a>
    </div>
</div>
<?php } ?>

<script>
    require([
        "jquery",
        "Magento_PageBuilder/js/resource/slick/slick",
        "domReady!"
    ], function ($) {
        $(window).load(function() {
             setTimeout(function () {
                 $('.post-list-slick').slick({
                    dots: false,
                    arrows: false,
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    autoplay: false,
                    infinite: false,
                    responsive: [{
                        breakpoint: 1200,
                            settings: {
                                slidesToShow: 3,
                                slidesToScroll: 1
                            }
                        },
                        {
                        breakpoint: 767,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 1,
                                infinite: false,
                            }
                        },
                        {
                        breakpoint: 640,
                            settings: {
                                slidesToShow: 1,
                                slidesToScroll: 1,
                                infinite: false,
                            }
                        }
                    ]
                });
            }, 0);
        });
    });
</script>