<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar posts list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\AbstractList
 */
?>

<?php
$_postCollection = $block->getPostCollection();?>
<?php
$widthImg = (int)$block->getBackgroundImageWidth() ?: 1000;
$width = (int)$block->getBlockImageWidth() ?: 300;
$height = (int)$block->getBlockImageheight() ?: 200;
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>
<?php if ($_postCollection->count()) { ?>
    <div class="widget block block-<?= $block->escapeHtml(str_replace('_', '-', $block->getWidgetKey())) ?> block-list-posts">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getBlockTitle() ?: 'Related Posts')) ?></strong>
        </div>
        <div class="block-content">
            <!-- post list -->
            <div class="post-list">
                <?php foreach ($_postCollection as $_post) { ?>
                    <?php
                    $_postUrl = $block->escapeUrl($_post->getPostUrl());
                    $_postName = $block->escapeHtml($_post->getTitle());
                    $comment_count = $_post->getCommentsCount() ? $_post->getCommentsCount() : 0;  
                    ?>
                    <!-- post item -->
                    <div class="post-item d-flex mb-4">
                        <?php
                         if ($block->getDisplayImage()) { ?>
                            <div class="image-container">
                                <a class="image-wrap _4x3" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                                    <?php
                                    $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                    if ($featuredImage) {
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($widthImg, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                    } else {
                                        $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/samples/' . rand(1, 8) . '.jpeg');
                                        $featuredImgAlt  = '';
                                    }
                                    ?>
                                    <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                </a>
                            </div>
                        <?php } ?>
                        <div class="block-info px-3">
                            <h3 class="post-title m-0 mb-2">
                                <a class="post-item-name" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                                    <?= $_postName ?>
                                </a>
                            </h3>
                            <?php if ($block->getDisplayImage() && $_post->isPublishDateEnabled()) { ?>
                                <div class="block-date">
                                    <span class="post-date"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <div class="comment-counter"><strong> - </strong><span class="cmt-count"><?= $block->escapeHtml($comment_count) ?> </span></div>
                                </div>
                            <?php } ?>
                            <div class="post-description d-none"></div>
                            <div class="read-more d-none"></div>
                        </div>
                    </div>
                    <!-- END post item -->
                <?php } ?>
            </div>
            <!-- END post list -->
        </div>
    </div>
<?php } ?>