<?php

// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $escaper \Magento\Framework\Escaper
 */
/** @var \Avalara\Excise\Block\Adminhtml\System\Config\Validateavataxlicense $block */
?>
<script>
    require([
        'Magento_Ui/js/modal/alert',
        'prototype'
    ], function(alert) {

        //<![CDATA[
        /**
         * Returns the scope from the form action to determine how to load the save config settings
         *
         * @returns {Object}
         */
        function getScope() {
            var formScope = document.getElementById('config-edit-form').action.match(/section\/\w+\/(website|store)\/(\d+)/i);

            if (formScope === null) {
                return {
                    scope_type: 'global'
                };
            }

            return {
                scope: formScope[2],
                scope_type: formScope[1]
            };
        }


        function validateAvataxLicense() {
            var validationMessage = $('validation_result_2');
            var accntNo = $('<?= $escaper->escapeJs($block->getAvataxAccountNoField()) ?>').value;
            var key = $('<?= $escaper->escapeJs($block->getAvataxLicenseKeyField()) ?>').value;

            if (accntNo == "" || key == "") {
                alert({
                    content: "<?= __('Please enter the credentials') ?>"
                });
                return;
            }

            var scopeData = getScope();

            params = {
                account_number: accntNo,
                licence_key: key,
                mode: $('<?= $escaper->escapeJs($block->getCurrentMode()) ?>').value,
                scope_id: scopeData.scope,
                scope_type: scopeData.scope_type
            };

            new Ajax.Request('<?= $escaper->escapeJs($escaper->escapeUrl($block->getAjaxUrl())) ?>', {
                parameters: params,
                onSuccess: function(response) {
                    var result = '<?= $escaper->escapeJs($escaper->escapeHtml(__('Error during Avatax License verification.'))) ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.valid == 1) {
                            validationMessage.removeClassName('hidden');
                            validationMessage.removeClassName('error');
                            validationMessage.addClassName('success');
                        } else {
                            validationMessage.removeClassName('success');
                            validationMessage.removeClassName('hidden').addClassName('error');
                        }
                    } catch (e) {
                        validationMessage.removeClassName('success');
                        validationMessage.removeClassName('hidden').addClassName('error');
                    }
                    validationMessage.update(result);
                }
            });
        }

        window.validateAvataxLicense = validateAvataxLicense;
        //]]>

    });
</script>
<div class="actions actions-validate-avatax-license">
    <button onclick="javascript:validateAvataxLicense(); return false;" class="action-validate-avatax-license" type="button" id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="validation_result_2" class="message-validation hidden"></div>
</div>
<style>
    .success {
        color: green;
    }

    .error {
        color: red;
    }
</style>