<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $block->escapeUrl($_post->getPostUrl());
$_postName = $block->escapeHtml($_post->getTitle());
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?>">
    <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
    <?php if ($featuredImage) { ?>
        <?php
        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
        if (!$featuredImgAlt) {
            $featuredImgAlt = $_postName;
        }
        ?>
        <div class="post-ftimg-hld">
            <a href="<?= /*@noEscape*/ $_postUrl ?>"
               title="<?= /*@noEscape*/ $_postName ?>">
                <img src="<?= $block->escapeUrl($featuredImage) ?>"
                     alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
            </a>
        </div>
    <?php } ?>
    <div class="post-content">
        <div class="post-info clear">
            <?php if ($_post->isPublishDateEnabled()) { ?>
                <div class="item post-posed-date">
                    <span class="posted-icon">
                        <img src="<?= $block->getViewFileUrl('images/calender-icon.svg'); ?>" alt="Calender" />
                    </span>
                    <span class="value">
                        <?= $block->escapeHtml(date('d/m/Y', strtotime($_post->getModifiedTime()))) ?>
                    </span>
                </div>
            <?php } ?>
             <!-- get Author name start -->
             <?php if ($block->authorEnabled()) { ?>
                    <?php if ($_author = $_post->getAuthor()) { ?>
                    <div class="item post-author">
                            <span class="label"><?= $block->escapeHtml(__('By:')) ?></span>
                            <span class="value">
                            <?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
                            <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                               href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>">
                            <?php } ?>

                            <?= $block->escapeHtml($_author->getTitle()) ?>

                            <?php if ($authorPageEnabled) { ?>
                            </a>
                            <?php } ?>
                        </span>
                    </div>
                    <?php } ?>
                <?php } ?>
            <!-- End Author name -->
        </div>
        <div class="post-title-holder clearfix">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?= /*@noEscape*/ $_postUrl ?>">
                    <?= /*@noEscape*/ $_postName ?>
                </a>
            </h2>
        </div>
        <div class="post-description clearfix">
            <?= /*@noEscape*/ $block->getShorContent() ?>
        </div>
        <a class="post-read-more"
           href="<?= /*@noEscape*/ $_postUrl ?>"
           title="<?= /*@noEscape*/ $_postName ?>">
            <?= $block->escapeHtml(__('Read more')) ?>
            <span class="svg_icon">
                <svg width="10" height="14" viewBox="0 0 6 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1L5 5L1 9" stroke="#838282" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </span>
        </a>
    </div>
    <div class="post-footer">

    </div>
</li>
